'use strict';
// Auto-generated from giac aide_cas — do not edit manually
// Generated: 2026-03-01
// Language: Arabic (ar)
// Commands: 1731 | Aliases: 481 | Descriptions: 0 (0.0%)
// Source: https://raw.githubusercontent.com/s-celles/giac/main/doc/aide_cas

var GIAC_HELP = {
  cmds: {
    '!':{d:'',p:'Boolean'},
    '!=':{d:'',p:'Expr,Expr'},
    '#':{d:'',p:'Str'},
    '$':{d:'',p:'(Expr(Var)||Int(a..b)),(Var(Var)=Int(a..b))||Intg(n)||Real(p)'},
    '%/':{d:'',p:'Intg(a),Intg(b)'},
    '&*':{d:'',p:'Mtrx,Mtrx'},
    '&^':{d:'',p:'Mtrx,Intg(n)'},
    '\'':{d:'',p:'Strng(str)'},
    '()':{d:''},
    '*':{d:'',p:'Vect,Vect||Mtrx,Mtrx,||Xpr,Xpr'},
    '*=':{d:'',p:'Var,Real'},
    '+':{d:'',p:'Str||Lst||Expr||Pnt, Str||Lst||Expr||Pnt'},
    '+&':{d:'',p:'Str||Lst, Str||Lst, Expr||Expr'},
    '+=':{d:'',p:'Var,(Real or Str)'},
    '+infinity':{d:'',a:['inf']},
    '-':{d:'',p:'Lst||Expr||Pnt,Lst||Expr||Pnt'},
    '-<':{d:'',p:'GeoObj,Attribut'},
    '-=':{d:'',p:'Var,Real'},
    '->':{d:'',p:'VectVar(x),Expr(f(x))'},
    '-infinity':{d:''},
    '.*':{d:'',p:'Lst||Mtrx,Lst||Mtrx'},
    '.+':{d:'',p:'Lst||Mtrx, Real(a)||Lst||Mtrx'},
    '.-':{d:'',p:'Lst||Mtrx,Real(a)||Lst||Mtrx'},
    './':{d:'',p:'Lst||Mtrx,Lst||Mtrx'},
    '.^':{d:'',p:'Mtrx,Intg(n)'},
    '/%':{d:''},
    '/=':{d:'',p:'Var,Real'},
    ':=':{d:'',p:'Var,(Real or Str)'},
    '<':{d:'',p:'Expr,Expr'},
    '<=':{d:'',p:'Expr,Expr'},
    '=':{d:'',p:'Expr,Expr'},
    '=<':{d:'',p:'Var,(Real or Str)'},
    '==':{d:'',p:'Expr,Expr'},
    '=>':{d:'',p:'(Real or Str),Var'},
    '>':{d:'',p:'Expr,Expr'},
    '>=':{d:'',p:'Expr,Expr'},
    '?':{d:'',p:'Cond,Expr1,Expr2'},
    '@':{d:'',p:'Fnc,Fnc'},
    '@@':{d:'',p:'Fnc(f),Intg(n)'},
    'Airy_Ai':{d:'',p:'Real'},
    'Airy_Bi':{d:'',p:'Real'},
    'Archive':{d:'',p:'SeqVar'},
    'BesselJ':{d:'',p:'Int(p),Real(x)'},
    'BesselY':{d:'',p:'Int(p),Real(x)'},
    'Beta':{d:'',p:'Expr,Expr,[Expr],[1]'},
    'BlockDiagonal':{d:'',p:'Lst(l)||Mtrx(A)'},
    'COND':{d:'',p:'Mtrx,[2]||[inf]',a:['cond']},
    'CST':{d:'',p:'Lst'},
    'Celsius2Fahrenheit':{d:'',p:'Unit'},
    'Ci':{d:'',p:'Expr'},
    'Circle':{d:'',p:'Real(xc),Real(yc),Real(r),[Intg(option)]'},
    'ClrGraph':{d:'',p:'NULL',a:['ClrDraw']},
    'ClrIO':{d:'',p:'NULL'},
    'Col':{d:'',p:'NULL'},
    'CopyVar':{d:'',p:'Var(var1),Var(var2)'},
    'CyclePic':{d:'',p:'Str(),Intg(n),Real(p),Intg(n)'},
    'DOM_COMPLEX':{d:'',p:'Opt',a:['complex']},
    'DOM_FLOAT':{d:'',p:'Opt',a:['float','double']},
    'DOM_FUNC':{d:'',p:'Opt',a:['func']},
    'DOM_IDENT':{d:'',p:'Opt',a:['identifier']},
    'DOM_INT':{d:'',p:'Opt',a:['integer','DOM_int']},
    'DOM_LIST':{d:'',p:'Opt',a:['vector']},
    'DOM_RAT':{d:'',p:'Opt',a:['rational']},
    'DOM_STRING':{d:'',p:'Opt',a:['string']},
    'DOM_SYMBOLIC':{d:'',p:'Opt',a:['symbol','expression']},
    'DelFold':{d:'',p:'Var'},
    'Det':{d:'',p:'Mtrx'},
    'Dialog':{d:'',p:'Title;Text;Request;Request;DropDown;EndDlog',a:['EndDlog']},
    'Digits':{d:'',p:':=Intg(n)',a:['DIGITS']},
    'Dirac':{d:'',p:'Real'},
    'DispG':{d:''},
    'DispHome':{d:''},
    'DrawInv':{d:'',p:'Expr,[Var]'},
    'DrawSlp':{d:'',p:'Real(a),Real(b),Real(m)'},
    'DropDown':{d:'',p:'Str,LstVal,Var'},
    'Ei':{d:'',p:'Expr'},
    'Factor':{d:'',p:'Expr'},
    'Fahrenheit2Celsius':{d:'',p:'Unit'},
    'Fill':{d:'',p:'Expr(Xpr),Var(A)'},
    'Fourier':{d:'',p:'Expr(f),Var(t),Var(omega)'},
    'GF':{d:'',p:'Intg(p), Intg(n)|Minpoly,[Variable],[0|undef|Poly]'},
    'Gamma':{d:'',p:'Real(a),[Real(b)]'},
    'Gcd':{d:'',p:'(Intg or Poly),(Intg or Poly)'},
    'GetFold':{d:'',p:'Var'},
    'Heaviside':{d:'',p:'Real'},
    'Heaviside2sign':{d:'',p:'Expr'},
    'Hilbert':{d:'',p:'Expr(f),Var(x)'},
    'InputStr':{d:'',p:'[Str],Var(Var)',a:['textinput','lis_phrase']},
    'Int':{d:'',p:'Expr,[Var(x)],[Real(a)],[Real(b)]'},
    'Inverse':{d:'',p:'Expr||Mtrx'},
    'JordanBlock':{d:'',p:'Expr(a),Intg(n)'},
    'LQ':{d:'',p:'Mtrx(A)'},
    'LSQ':{d:'',p:'Mtrx(A),(Mtrx || Vect)(B)',a:['lsq']},
    'LU':{d:'',p:'Mtrx(A),Var(L),Var(U),Var(P)'},
    'LambertW':{d:'',p:'Real(x),[Intg(n)]'},
    'Li':{d:'',p:'Expr'},
    'Line':{d:'',p:'Expr(a),Expr(b),Expr(c),Expr(d)'},
    'LineHorz':{d:'',p:'Expr(a)'},
    'LineTan':{d:'',p:'Expr(f(x)),[Var],Expr(a)'},
    'LineVert':{d:'',p:'Expr(a)'},
    'MSE':{d:'',p:'Opt',a:['cross_entropy','log_loss','ReLU','learning_rate','weight_decay','block_size','adaptive','momentum','topology']},
    'NewFold':{d:'',p:'Var'},
    'NewPic':{d:'',p:'Mtrx_nrows_2cols(A),Var(pic1)'},
    'Nullspace':{d:'',p:'Mtrx'},
    'Ox_2d_unit_vector':{d:'',p:'NULL'},
    'Ox_3d_unit_vector':{d:'',p:'NULL'},
    'Oy_2d_unit_vector':{d:'',p:'NULL'},
    'Oy_3d_unit_vector':{d:'',p:'NULL'},
    'Oz_3d_unit_vector':{d:'',p:'NULL'},
    'Pause':{d:'',a:['sleep']},
    'Psi':{d:'',p:'Real(a),Intg(n)'},
    'QR':{d:'',p:'Mtrx,Var(Q),Var(R),[Real(eps)]'},
    'Quo':{d:'',p:'(Vect or Poly),(Vect or Poly),[Var]'},
    'REDIM':{d:'',p:'Mtrx||Vect,Intg(n1),Intg(n2)',a:['redim']},
    'REPLACE':{d:'',p:'Mtrx(A),Lst(n1,n2),Mtrx(B)',a:['replace']},
    'RandSeed':{d:'',p:'Intg'},
    'RclPic':{d:'',p:'Var(pic1)'},
    'Rem':{d:'',p:'(Vect or Poly),(Vect or Poly),[Var]'},
    'Request':{d:'',p:'Str,Var'},
    'Resultant':{d:'',p:'Poly,Poly,Var'},
    'Row':{d:'',p:'NULL'},
    'RplcPic':{d:'',p:'Var(pic1)'},
    'Rref':{d:'',p:'Mtrx(M)'},
    'SCHUR':{d:'',p:'Mtrx(A)',a:['schur']},
    'SVD':{d:'',p:'Mtrx(A)'},
    'SVL':{d:'',p:'Mtrx(A)'},
    'SetFold':{d:'',p:'Var'},
    'Si':{d:'',p:'Expr'},
    'SortA':{d:'',p:'LstReal||Seq||Mtrx'},
    'SortD':{d:'',p:'LstReal||Seq||Mtrx'},
    'StoPic':{d:'',p:'Var'},
    'Text':{d:'',p:'Str'},
    'Title':{d:'',p:'Str'},
    'UTPC':{d:'',p:'Intg(n),Real(x0)'},
    'UTPF':{d:''},
    'UTPN':{d:'',p:'Real(mu),Real(v),Real(x0)'},
    'UTPT':{d:'',p:'Intg(n),Real(x0)'},
    'Unarchiv':{d:'',p:'SeqVar'},
    'VARS':{d:'',p:'NULL'},
    'VAS':{d:'',p:'Poly(P)'},
    'VAS_positive':{d:'',p:'Poly(P)'},
    'WAIT':{d:'',p:'Var(n)'},
    'Zeta':{d:'',p:'Real(a)'},
    '^':{d:'',p:'Expr(a),Intg(n)'},
    '_(cm/s)':{d:''},
    '_(ft*lb)':{d:''},
    '_(ft/s)':{d:''},
    '_(m/s)':{d:''},
    '_(m/s^2)':{d:''},
    '_(rad/s)':{d:''},
    '_(rad/s^2)':{d:''},
    '_(tr/min)':{d:''},
    '_(tr/s)':{d:''},
    '_A':{d:''},
    '_Angstrom':{d:''},
    '_Bq':{d:''},
    '_Btu':{d:''},
    '_Ci':{d:''},
    '_F':{d:''},
    '_F_':{d:''},
    '_Fdy':{d:''},
    '_G_':{d:''},
    '_Gal':{d:''},
    '_Gy':{d:''},
    '_H':{d:''},
    '_Hz':{d:''},
    '_J':{d:''},
    '_K':{d:''},
    '_Kcal':{d:''},
    '_MHz':{d:''},
    '_MW':{d:''},
    '_MeV':{d:''},
    '_N':{d:''},
    '_NA_':{d:''},
    '_Ohm':{d:''},
    '_P':{d:''},
    '_PSun_':{d:''},
    '_Pa':{d:''},
    '_R':{d:''},
    '_REarth_':{d:''},
    '_RSun_':{d:''},
    '_R_':{d:''},
    '_Rankine':{d:''},
    '_Rinfinity_':{d:''},
    '_S':{d:''},
    '_St':{d:''},
    '_StdP_':{d:''},
    '_StdT_':{d:''},
    '_Sv':{d:''},
    '_T':{d:''},
    '_V':{d:''},
    '_Vm_':{d:''},
    '_W':{d:''},
    '_Wb':{d:''},
    '_Wh':{d:''},
    '_a':{d:''},
    '_a0_':{d:''},
    '_acre':{d:''},
    '_alpha_':{d:''},
    '_arcmin':{d:''},
    '_arcs':{d:''},
    '_atm':{d:''},
    '_au':{d:''},
    '_b':{d:''},
    '_bar':{d:''},
    '_bbl':{d:''},
    '_bblep':{d:''},
    '_bu':{d:''},
    '_buUS':{d:''},
    '_c3_':{d:''},
    '_c_':{d:''},
    '_cal':{d:''},
    '_cd':{d:''},
    '_chain':{d:''},
    '_cm':{d:''},
    '_cm^2':{d:''},
    '_cm^3':{d:''},
    '_ct':{d:''},
    '_cu':{d:''},
    '_d':{d:''},
    '_dB':{d:''},
    '_deg':{d:''},
    '_degreeF':{d:''},
    '_dyn':{d:''},
    '_eV':{d:''},
    '_epsilon0_':{d:''},
    '_epsilon0q_':{d:''},
    '_epsilonox_':{d:''},
    '_epsilonsi_':{d:''},
    '_erg':{d:''},
    '_f0_':{d:''},
    '_fath':{d:''},
    '_fbm':{d:''},
    '_fc':{d:''},
    '_fermi':{d:''},
    '_flam':{d:''},
    '_fm':{d:''},
    '_ft':{d:''},
    '_ftUS':{d:''},
    '_ft^2':{d:''},
    '_ft^3':{d:''},
    '_g':{d:''},
    '_g_':{d:''},
    '_ga':{d:''},
    '_galC':{d:''},
    '_galUK':{d:''},
    '_galUS':{d:''},
    '_gf':{d:''},
    '_gmol':{d:''},
    '_gon':{d:''},
    '_grad':{d:''},
    '_grain':{d:''},
    '_h':{d:''},
    '_h_':{d:''},
    '_ha':{d:''},
    '_hbar_':{d:''},
    '_hp':{d:''},
    '_in':{d:''},
    '_inH20':{d:''},
    '_inHg':{d:''},
    '_in^2':{d:''},
    '_in^3':{d:''},
    '_j':{d:''},
    '_kWh':{d:''},
    '_k_':{d:''},
    '_kg':{d:''},
    '_kip':{d:''},
    '_km':{d:''},
    '_km^2':{d:''},
    '_knot':{d:''},
    '_kph':{d:''},
    '_kq_':{d:''},
    '_l':{d:''},
    '_lam':{d:''},
    '_lambda0_':{d:''},
    '_lambdac_':{d:''},
    '_lb':{d:''},
    '_lbf':{d:''},
    '_lbmol':{d:''},
    '_lbt':{d:''},
    '_lep':{d:''},
    '_liqpt':{d:''},
    '_lm':{d:''},
    '_lx':{d:''},
    '_lyr':{d:''},
    '_m':{d:''},
    '_mEarth_':{d:''},
    '_m^2':{d:''},
    '_m^3':{d:''},
    '_me_':{d:''},
    '_mho':{d:''},
    '_miUS':{d:''},
    '_miUS^2':{d:''},
    '_mi^2':{d:''},
    '_mil':{d:''},
    '_mile':{d:''},
    '_mille':{d:''},
    '_ml':{d:''},
    '_mm':{d:''},
    '_mmHg':{d:''},
    '_mn':{d:''},
    '_mol':{d:''},
    '_mp_':{d:''},
    '_mph':{d:''},
    '_mpme_':{d:''},
    '_mu0_':{d:''},
    '_muB_':{d:''},
    '_muN_':{d:''},
    '_oz':{d:''},
    '_ozUK':{d:''},
    '_ozfl':{d:''},
    '_ozt':{d:''},
    '_pc':{d:''},
    '_pdl':{d:''},
    '_ph':{d:''},
    '_phi_':{d:''},
    '_pk':{d:''},
    '_psi':{d:''},
    '_ptUK':{d:''},
    '_qe_':{d:''},
    '_qepsilon0_':{d:''},
    '_qme_':{d:''},
    '_qt':{d:''},
    '_rad':{d:''},
    '_rad_':{d:''},
    '_rd':{d:''},
    '_rem':{d:''},
    '_rod':{d:''},
    '_rpm':{d:''},
    '_s':{d:''},
    '_sb':{d:''},
    '_sd_':{d:''},
    '_sigma_':{d:''},
    '_slug':{d:''},
    '_sr':{d:''},
    '_st':{d:''},
    '_syr_':{d:''},
    '_t':{d:''},
    '_tbsp':{d:''},
    '_tec':{d:''},
    '_tep':{d:''},
    '_tex':{d:''},
    '_therm':{d:''},
    '_ton':{d:''},
    '_tonUK':{d:''},
    '_torr':{d:''},
    '_tr':{d:''},
    '_tsp':{d:''},
    '_u':{d:''},
    '_yd':{d:''},
    '_yd^2':{d:''},
    '_yd^3':{d:''},
    '_yr':{d:''},
    '_µ':{d:''},
    'a2q':{d:'',p:'Mtrx,VectVar'},
    'abcuv':{d:'',p:'Poly(a),Poly(b),Poly(c),[Var]'},
    'about':{d:'',p:'Var(a)||Image||Audio'},
    'abs':{d:'',p:'Cplx||LstCplx'},
    'abscissa':{d:'',p:'Pnt or Vect'},
    'accumulate_head_tail':{d:'',p:'Lst(l),Intg(p),Intg(q)'},
    'acos':{d:'',p:'Expr',a:['arccos']},
    'acos2asin':{d:'',p:'Expr'},
    'acos2atan':{d:'',p:'Expr'},
    'acosh':{d:'',p:'Expr',a:['arccosh','ACOSH']},
    'acot':{d:'',p:'Expr',a:['ACOT']},
    'acsc':{d:'',p:'Expr',a:['ACSC']},
    'acyclic':{d:'',p:'Opt'},
    'add_arc':{d:'',p:'Graph(G),Edge(e)||Trail(T)||Lst(E)'},
    'add_edge':{d:'',p:'Graph(G),Edge(e)||Trail(T)||Lst(E)'},
    'add_vertex':{d:'',p:'Graph(G),Vrtx(v)||Lst(V)'},
    'additionally':{d:'',p:'Expr'},
    'addtable':{d:'',p:'fourier||laplace,f(x),F(s),Var(x),Var(s)'},
    'adjacency_matrix':{d:'',p:'Graph(G)'},
    'adjoint_matrix':{d:'',p:'Mtrx'},
    'affix':{d:'',p:'Pnt||Vect'},
    'algsubs':{d:'',p:'Equal(Xpr1=Xpr2),Expr(Xpr)'},
    'algvar':{d:'',p:'Expr'},
    'all_trig_solutions':{d:'',p:':=Intg(0 or 1)'},
    'allpairs_distance':{d:'',p:'Graph(G)'},
    'alog10':{d:'',p:'Expr'},
    'altitude':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),(Pnt or Cplx)'},
    'and':{d:'',p:'Expr, Expr',a:['&&','et']},
    'angle':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),(Pnt or Cplx)'},
    'angle_radian':{d:'',p:':=Intg(0 or 1)'},
    'angleat':{d:'',p:'Pnt(A),Pnt(B),Pnt(C),(Pnt or Cplx(z0))'},
    'angleatraw':{d:'',p:'Pnt(A),Pnt(B),Pnt(C),(Pnt or Cplx(z0))'},
    'animate':{d:'',p:'Expr(Xpr),x=xmin..xmax,t=tmin..tmax,frames=nframes'},
    'animate3d':{d:'',p:'Expr(Xpr),[x=xmin..xmax,y=ymin..ymax],t=tmin..tmax,frames=nframes'},
    'animation':{d:'',p:'Mtrx'},
    'ans':{d:'',p:'Intg(n)'},
    'antiprism_graph':{d:'',p:'Intg(n)'},
    'append':{d:'',p:'(Lst||Set||Str(L),Elem)'},
    'apply':{d:'',p:'Fnc(f),Lst(l)'},
    'approx_mode':{d:'',p:':=Intg(0 or 1)'},
    'arc':{d:'',p:'Pnt, Pnt, Real,[Var(C)],[Var(r)],[Opt(segment)]'},
    'arcLen':{d:'',p:'Expr(Xpr) or Lst([Xpr1,Xpr2]),Var,Real(a),Real(b)',a:['arclen']},
    'archive':{d:'',p:'Str(namefich),Seq(Var)'},
    'area':{d:'',p:'Polygone || Expr,x=a..b,[n],[Method]'},
    'areaat':{d:'',p:'Polygone, Pnt||Cplx(z0)'},
    'areaatraw':{d:'',p:'Polygone, Pnt||Cplx(z0)'},
    'arg':{d:'',p:'Expr'},
    'args':{d:'',p:'NULL'},
    'array':{d:'',p:'Opt'},
    'arrivals':{d:'',p:'Graph(G),[Vrtx(v)]'},
    'articulation_points':{d:'',p:'Graph(G)'},
    'as_function_of':{d:'',p:'VarResult,VarArg'},
    'asc':{d:'',p:'Str'},
    'asec':{d:'',p:'Expr',a:['ASEC']},
    'asin':{d:'',p:'Expr',a:['arcsin','ASIN']},
    'asin2acos':{d:'',p:'Expr'},
    'asin2atan':{d:'',p:'Expr'},
    'asinh':{d:'',p:'Expr',a:['arcsinh','ASINH']},
    'assert':{d:'',p:'Boolean(b)'},
    'assign':{d:'',p:'(Var,value) or Equal or LstEq.'},
    'assign_edge_weights':{d:'',p:'Graph(G),Seq(m,n)||Intrv(a..b)'},
    'assume':{d:'',p:'Expr'},
    'at':{d:'',p:'Lst(l)||Mtrx(m),Index(j)||Lst([j,k])'},
    'atan':{d:'',p:'Expr',a:['arctan','ATAN']},
    'atan2':{d:'',p:'Real(y),Real(x)'},
    'atan2acos':{d:'',p:'Expr'},
    'atan2asin':{d:'',p:'Expr'},
    'atanh':{d:'',p:'Expr',a:['arctanh','ATANH']},
    'atrig2ln':{d:'',p:'Expr'},
    'auto_correlation':{d:'',p:'Lst'},
    'autosimplify':{d:'',p:'Cmds'},
    'avance':{d:'',p:'NULL or Real(n)',a:['forward']},
    'avgRC':{d:'',p:'Expr(Xpr),Var(Var),[Real(h)]'},
    'axes':{d:'',p:'Opt'},
    'axis':{d:'',p:'xmin,xmax,ymin,ymax,[zmin,zmaz]'},
    'back':{d:'',p:'Vect or Seq or Str'},
    'backquote':{d:'',p:'Expr'},
    'baisse_crayon':{d:'',p:'NULL',a:['pendown']},
    'bandwidth':{d:'',p:'Opt'},
    'bar_plot':{d:'',p:'Mtrx',a:['barplot']},
    'bartlett_hann_window':{d:'',p:'Lst,[Interval(n1..n2)]'},
    'barycenter':{d:'',p:'[Pnt,Real],[Pnt,Real],[Pnt,Real]'},
    'base':{d:'',p:'Opt'},
    'basis':{d:'',p:'Lst(vector1,..,vectorn)'},
    'batons':{d:'',p:'Mtrx'},
    'begin':{d:''},
    'bellman_ford':{d:'',p:'Graph(G),Vrtx(s),Vrtx(t)||Lst(T)'},
    'bernoulli':{d:'',p:'Intg||(Intg,Var)'},
    'bernoulli_mod':{d:'',p:'Intg,Intg'},
    'besselJ':{d:'',p:'Real(x),Int(p)'},
    'besselY':{d:'',p:'Real(x),Int(p)'},
    'betad':{d:'',p:'Real(a>0),Real(b>0),Real(0<=x<=1)'},
    'betad_cdf':{d:'',p:'Real(a>0),Real(b>0),Real(0<=x0<=1),[Real(0<=y0<=1)]'},
    'betad_icdf':{d:'',p:'Real(a>0),Real(b>0),Real(0<=p<=1)'},
    'betweenness_centrality':{d:'',p:'Graph(G),[Vrtx(v)]'},
    'bezier':{d:'',p:'Lst,[plot]'},
    'bezoutian':{d:'',p:'Poly,Poly'},
    'biconnected_components':{d:'',p:'Graph(G)'},
    'binomial':{d:'',p:'Intg(n),Intg(k),[Real(p in 0..1)]'},
    'binomial_cdf':{d:'',p:'Intg(n),Real(p),Real(x),[Real(y)]'},
    'binomial_icdf':{d:'',p:'Intg(n),Real(p),Real(t)'},
    'bins':{d:'',p:'Opt'},
    'bipartite':{d:'',p:'Opt'},
    'bipartite_matching':{d:'',p:'Graph(G,[maximize||minimize,[epsilon=Real(eps)]])'},
    'bisection_solver':{d:'',p:'Opt',a:['brent_solver','falsepos_solver','newton_solver','secant_solver','steffenson_solver']},
    'bisector':{d:'',p:'(Pnt(A) or Cplx),(Pnt(B) or Cplx),(Pnt(C) or Cplx)'},
    'bit_depth':{d:'',p:'Audio(clip)||Image(img)'},
    'bitand':{d:'',p:'Intg,Intg'},
    'bitor':{d:'',p:'Intg,Intg'},
    'bitxor':{d:'',p:'Intg,Intg'},
    'blackman_harris_window':{d:'',p:'Lst,[Interval(n1..n2)]'},
    'blackman_window':{d:'',p:'Lst,[Real(a)],[Interval(n1..n2)]'},
    'bloc':{d:''},
    'blockmatrix':{d:'',p:'Intg(n),Intg(m),Lst'},
    'bohman_window':{d:'',p:'Lst,[Interval(n1..n2)]'},
    'border':{d:'',p:'Mtrx(A),Lst(b)'},
    'box_constraints':{d:'',p:'Vect(x),Mtrx(bounds)'},
    'boxcar':{d:'',p:'Real(a),Real(b),Expr(x)'},
    'boxwhisker':{d:'',p:'Lst,[Lst],[x=a..b||y=a..b]',a:['moustache']},
    'break':{d:''},
    'breakpoint':{d:'',p:'Intg'},
    'bspline':{d:'',p:'Lst(c),[x[=Lst(t)||a..b],Intg(p)]'},
    'bvpsolve':{d:'',p:'Expr(f(x,y,y\')),Lst(x=a..b,y),Lst(y(a),y(b),[y\'(1)]),[options]'},
    'c1oc2':{d:'',p:'Cycle,Cycle'},
    'c1op2':{d:'',p:'Cycle,Permut'},
    'cFactor':{d:'',p:'Expr',a:['cfactor','factoriser_sur_C']},
    'cZeros':{d:'',p:'Expr(Xpr)||LstExpr, [Var||LstVar]'},
    'cache_tortue':{d:'',p:'NULL'},
    'camembert':{d:'',p:'Mtrx',a:['pie']},
    'canonical_form':{d:'',p:'Trinom(a*x^2+b*x+c),[Var]'},
    'canonical_labeling':{d:'',p:'Graph(G)'},
    'cap':{d:'',p:'NULL or Real',a:['heading']},
    'cartesian_product':{d:'',p:'Seq(G1,G2,[G3])'},
    'cas_setup':{d:'',p:'Int,Int,Int,Int,Int,Real,Int'},
    'case':{d:''},
    'cat':{d:'',p:'SeqObj'},
    'catch':{d:'',p:'Var'},
    'cauchy':{d:'',p:'Real(x0),Real(a),Real(x)',a:['cauchyd']},
    'cauchy_cdf':{d:'',p:'Real(x0),Real(a),Real(x),[Real(y)]',a:['cauchyd_cdf']},
    'cauchy_icdf':{d:'',p:'Real(x0),Real(a),Real(p)',a:['cauchyd_icdf']},
    'cd':{d:'',p:'Str'},
    'cdf':{d:'',p:'Func,FuncParams'},
    'ceil':{d:'',p:'Real or Cplx',a:['ceiling']},
    'center':{d:'',p:'Crcle'},
    'center2interval':{d:'',p:'LstVal(l),[Real(a0)]'},
    'centered_cube':{d:'',p:'Pnt(A),Pnt(B),Pnt(C)'},
    'centered_tetrahedron':{d:'',p:'Pnt(A),Pnt(B),Pnt(C)'},
    'cfsolve':{d:'',p:'Expr,Var,[Guess or Interval],[Method]'},
    'changebase':{d:'',p:'Mtrx(A),Mtrx(P)'},
    'channel_data':{d:'',p:'Audio(clip),[Intg(chn) or matrix],[range=a..b]||Image(img),Intg(chn),Intg(x),Intg(y),Intg(width),Intg(height)'},
    'channels':{d:'',p:'Audio(clip)||Image(img)'},
    'char':{d:'',p:'Intg or Lst(Intg)',a:['chr']},
    'chinrem':{d:'',p:'[Lst||Expr,Lst||Expr],[Lst||Expr,Lst||Expr]'},
    'chisquare':{d:'',p:'Intg(n),Real(x0)',a:['chisquared']},
    'chisquare_cdf':{d:'',p:'Intg(n),Real(x0)',a:['chisquared_cdf']},
    'chisquare_icdf':{d:'',p:'Intg(n),Real(p)',a:['chisquared_icdf']},
    'chisquaret':{d:'',p:'Data,[Func],[FuncParams]'},
    'choice':{d:'',p:'Lst(L)'},
    'cholesky':{d:'',p:'Mtrx'},
    'choosebox':{d:'',p:'Str(titel),LstVal,Var',a:['PopUp']},
    'chrem':{d:'',p:'LstIntg(a,b,c....),LstIntg(p,q,r,....)'},
    'chromatic_index':{d:'',p:'Graph(G)'},
    'chromatic_number':{d:'',p:'Graph(G)'},
    'chromatic_polynomial':{d:'',p:'Graph(G),[Var(t)]'},
    'circle':{d:'',p:'(Pnt(M) or Cplx(M),(Pnt(N) or Cplx(zN)),[Real(a)],[Real(b)],[Var(A)],[Var(B)]'},
    'circumcenter':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),((Pnt or Cplx)'},
    'circumcircle':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),((Pnt or Cplx)'},
    'classes':{d:'',p:'Lst(l),[ClassMin],[ClassSize||Lst(Center)]'},
    'clear':{d:'',p:'NULL'},
    'click':{d:'',p:'NULL'},
    'clique_cover':{d:'',p:'Graph(G),[Intg(k)]'},
    'clique_cover_number':{d:'',p:'Graph(G)'},
    'clique_number':{d:'',p:'Graph(G)'},
    'closeness_centrality':{d:'',p:'Graph(G),[Vrtx(v)]'},
    'cluster':{d:'',p:'Lst(data),[opts]'},
    'clustering_coefficient':{d:'',p:'Graph(G),[Vrtx(v)]'},
    'coeff':{d:'',p:'Expr(P),[Var]',a:['coeffs']},
    'col':{d:'',p:'Mtrx(A),Intg(n)||Interval(n1..n2)'},
    'colNorm':{d:'',p:'Vect or Mtrx',a:['colnorm']},
    'colSwap':{d:'',p:'Mtrx(A),Intg(n1),Intg(n2)',a:['swapcol','colswap','SWAPCOL']},
    'coldim':{d:'',p:'Mtrx',a:['ncols','colDim']},
    'collect':{d:'',p:'Poly or LstPoly'},
    'colormap':{d:'',p:'Str(palette)||Lst(palettes),[Intg(n)||Real(t)||Str(colorname)||display]'},
    'colspace':{d:'',p:'Mtrx(A), [Var(d)]'},
    'comDenom':{d:'',p:'Expr,[Var(Var)]'},
    'comb':{d:'',p:'Intg(n),Intg(r)',a:['nCr']},
    'combine':{d:'',p:'Expr(Xpr),Fnc(f).'},
    'comment':{d:'',p:'Expr'},
    'common_perpendicular':{d:'',p:'Line(D1),Line(D2)'},
    'companion':{d:'',p:'Poly,Var'},
    'compare':{d:'',p:'Obj(arg1),Obj(arg2)'},
    'complete_binary_tree':{d:'',p:'Intg(n)'},
    'complete_graph':{d:'',p:'Intg(n)||Lst(V)||Seq(n1,n2,...,nk)'},
    'complete_kary_tree':{d:'',p:'Intg(k),Intg(n)'},
    'complex_mode':{d:'',p:':=Intg(0 or 1)'},
    'complex_variables':{d:'',p:':=Intg(0 or 1)'},
    'complexroot':{d:'',p:'Poly(P),Real(l),[Cplx(a)],[Cplx(b)]'},
    'concat':{d:'',p:'Lst,Lst||Seq,Seq||Str,Str||Mtrx,Mtrx',a:['augment','extend']},
    'condensation':{d:'',p:'Graph(G)'},
    'cone':{d:'',p:'Pnt(A),Vect(v),Real(t),[Real(h)]'},
    'confrac':{d:'',p:'Opt'},
    'conic':{d:'',p:'Expr,[LstVar]'},
    'conj':{d:'',p:'Cplx'},
    'conjugate_equation':{d:'',p:'Expr(y0),Lst(P),Lst(V),Var(x),Real(a)'},
    'conjugate_gradient':{d:'',p:'Mtrx(A),Vect(y),[Vect(x0),Real(eps)]'},
    'connected':{d:'',p:'Opt'},
    'connected_components':{d:'',p:'Graph(G)'},
    'cont':{d:'',p:'NULL'},
    'contains':{d:'',p:'(Lst(l) or Set(l)),Elem(e)'},
    'content':{d:'',p:'Poly(P),[Var]'},
    'continue':{d:''},
    'contract_edge':{d:'',p:'Graph(G),Edge(e)'},
    'contract_subgraph':{d:'',p:'Graph(G),Lst(S),[lb]'},
    'convert':{d:'',p:'Expr(Xpr),Cmd(cmd)',a:['convertir']},
    'convex':{d:'',p:'Expr(f),Lst(x,y,..),[simplify]'},
    'convexhull':{d:'',p:'Lst'},
    'convolution':{d:'',p:'Lst(u),Lst(v)'},
    'coordinates':{d:'',p:'Pnt or Cplx or Vect'},
    'copy':{d:'',p:'Mtrx,Var'},
    'correlation':{d:'',p:'Lst||Mtrx,[Lst]'},
    'cos':{d:'',p:'Expr or Opt',a:['COS']},
    'cos2sintan':{d:'',p:'Expr'},
    'cosh':{d:'',p:'Expr',a:['COSH']},
    'cosine_window':{d:'',p:'Lst,[Real(a)],[Interval(n1..n2)]'},
    'cot':{d:'',p:'Expr',a:['COT']},
    'cote':{d:'',p:'Vect'},
    'count':{d:'',p:'Fnc(f)||LstIntg,(Lst||Mtrx)(l),[Opt(row||col)]'},
    'count_eq':{d:'',p:'Real(a),(Lst||Mtrx)(L),[Opt(row||col)]'},
    'count_inf':{d:'',p:'Real(a),(Lst||Mtrx)(L),[Opt(row||col)]'},
    'count_sup':{d:'',p:'Real(a),(Lst||Mtrx)(L),[Opt(row||col)]'},
    'covariance':{d:'',p:'Lst||Mtrx,[Lst]'},
    'covariance_correlation':{d:'',p:'Lst||Mtrx,[Lst]'},
    'cpartfrac':{d:'',p:'RatFrac'},
    'crationalroot':{d:'',p:'Poly(P)'},
    'crayon':{d:'',p:'Color',a:['pencolor']},
    'createwav':{d:'',p:'Lst(data),[opts]'},
    'cross':{d:'',p:'Vect(v1),Vect(v2)',a:['crossproduct','crossP']},
    'cross_correlation':{d:'',p:'cross_correlation(Lst(u),Lst(v))'},
    'cross_ratio':{d:'',p:'Pnt or Cplx(a),Pnt or Cplx(b),Pnt or Cplx(c),Pnt or Cplx(d)'},
    'csc':{d:'',p:'Expr',a:['CSC']},
    'csolve':{d:'',p:'LstEq,LstVar',a:['cSolve','resoudre_dans_C']},
    'csv2gen':{d:'',p:'Strng(filename),Strng(sep),Strng(nl),Strng(decsep),Strng(eof),[string]'},
    'cube':{d:'',p:'Pnt(A),Pnt(B),Pnt(C)'},
    'cumSum':{d:'',p:'Lst(l)||Seq||Str',a:['cumsum']},
    'cumulated_frequencies':{d:'',p:'Lst || Mtrx'},
    'curl':{d:'',p:'Lst(A,B,C),Lst(x,y,z)'},
    'current_sheet':{d:'',p:'[Intg||Inter],[Intg||Letter],[Letter]'},
    'curvature':{d:'',p:'Curve,Point'},
    'curve':{d:'',p:'Expr'},
    'cycle2perm':{d:'',p:'Cycle'},
    'cycle_basis':{d:'',p:'Graph(G)'},
    'cycle_graph':{d:'',p:'Intg(n)||Lst(V)'},
    'cycleinv':{d:'',p:'Cycle(c)'},
    'cycles2permu':{d:'',p:'Lst(Cycle)'},
    'cyclotomic':{d:'',p:'Expr'},
    'cylinder':{d:'',p:'Pnt(A),Vect(v),Real(r),[Real(h)]'},
    'dash_line':{d:'',p:'Opt',a:['ligne_tiret','solid_line','ligne_trait_plein','dashdot_line','ligne_tiret_point','dashdotdot_line','ligne_tiret_pointpoint','cap_flat_line','ligne_chapeau_plat','cap_square_line','ligne_chapeau_carre','cap_round_line','ligne_chapeau_rond']},
    'dayofweek':{d:'',p:'Int,Int,Int'},
    'de':{d:'',a:['from']},
    'debug':{d:'',p:'Expr'},
    'debut_enregistrement':{d:'',p:'Var(nom_du_dessin)'},
    'default':{d:'',a:['otherwise']},
    'degree':{d:'',p:'Poly(P),Var(Var)'},
    'degree_centrality':{d:'',p:'Graph(G),[Vrtx(v)]'},
    'degree_sequence':{d:'',p:'Graph(G)'},
    'degrees':{d:'',p:'Real(rad)'},
    'delcols':{d:'',p:'Mtrx(A),Interval(n1..n2)||n1'},
    'delete_arc':{d:'',p:'Graph(G),Edge(e)||Trail(T)||Lst(E)'},
    'delete_edge':{d:'',p:'Graph(G),Edge(e)||Trail(T)||Lst(E)'},
    'delete_vertex':{d:'',p:'Graph(G),Vrtx(v)||Lst(V)'},
    'delrows':{d:'',p:'Mtrx(A),Interval(n1..n2)||n1'},
    'deltalist':{d:'',p:'Lst'},
    'denom':{d:'',p:'Frac(a/b) or RatFrac'},
    'departures':{d:'',p:'Graph(G),[Vrtx(v)]'},
    'desolve':{d:'',p:'Eq,[TimeVar],FncVar',a:['deSolve','dsolve']},
    'dessine_tortue':{d:'',p:'[Intg(n)]'},
    'det':{d:'',p:'Mtrx'},
    'det_minor':{d:'',p:'Mtrx(A)'},
    'dfc':{d:'',p:'Real(x0),Int(n)||Real(eps)'},
    'dfc2f':{d:'',p:'LstFrac_Cont)'},
    'diag':{d:'',p:'Lst(l)||(Mtrx(A),[left||right||lu])||Lst(l),Lst(d),Lst(u)'},
    'diff':{d:'',p:'Expr or Fnc,[SeqVar or LstVar],[n]',a:['derive','deriver']},
    'digraph':{d:'',p:'[Lst(V)],[Set(E)],[Mtrx(A)],[options]'},
    'dijkstra':{d:'',p:'Graph(G),Vrtx(v),[Vrtx(w)||Lst(W)]'},
    'dim':{d:'',p:'Mtrx'},
    'directed':{d:'',p:'Opt'},
    'discard_edge_attribute':{d:'',p:'Graph(G),Edge(e),Seq(tag1=value1,tag2=value2,..)'},
    'discard_graph_attribute':{d:'',p:'Graph(G),Seq(tag1=value1,tag2=value2,..)'},
    'discard_vertex_attribute':{d:'',p:'Graph(G),Vrtx(v),Seq(tag1=value1,tag2=value2,..)'},
    'discriminant':{d:'',p:'Poly,Var'},
    'disjoint_union':{d:'',p:'Seq(G1,G2,...)'},
    'display':{d:'',p:'[GeoObj or legende],Intg',a:['color']},
    'disque':{d:'',p:'Real(r),[Real(a)],[Real(b)]'},
    'disque_centre':{d:'',p:'Real(r),[Real(a)],[Real(b)]'},
    'distance':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx or Curve)'},
    'distance2':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx or Curve)'},
    'distanceat':{d:'',p:'GeoObj(A),GeoObj(B),(Pnt or Cplx)'},
    'distanceatraw':{d:'',p:'GeoObj(A),GeoObj(B),(Pnt or Cplx(z0))'},
    'div':{d:'',p:'Intg,Intg'},
    'divergence':{d:'',p:'Lst(A,B,C),Lst(x,y,z)'},
    'divis':{d:'',p:'Poly(P) or LstPoly'},
    'division_point':{d:'',p:'Pnt or Cplx(a),Pnt or Cplx(b),Cplx(k)'},
    'divpc':{d:'',p:'Poly,Poly,Intg(n)'},
    'dnewton_solver':{d:'',p:'Opt',a:['hybrid_solver','hybrids_solver','hybridj_solver','hybridsj_solver','newtonj_solver']},
    'do':{d:'',a:['faire']},
    'dodecahedron':{d:'',p:'Pnt(A),Pnt(B),Pnt(C)'},
    'domain':{d:'',p:'Expr'},
    'dot':{d:'',p:'Vect(v1),Vect(v2)',a:['dotP','scalarProduct','scalar_product','dotprod']},
    'dot_paper':{d:'',p:'Real(ux),Real(uy),Real(t)'},
    'draw_arc':{d:'',p:'Intg(x),Intg(y),Intg(rx),Intg(ry),Real(theta1),Real(theta2),Intg(col)'},
    'draw_circle':{d:'',p:'Intg(x),Intg(y),Intg(r),Intg(col)'},
    'draw_graph':{d:'',p:'Graph(G),[opts]'},
    'draw_line':{d:'',p:'Intg(x1),Intg(y1),Intg(x2),Intg(y2),Intg(col)'},
    'draw_polygon':{d:'',p:'Lst(l),Intg(col)'},
    'draw_rectangle':{d:'',p:'Intg(x),Intg(y),Intg(w),Intg(h),Intg(col)'},
    'droite_tangente':{d:'',p:'Expr(f(x)),[Var],Expr(a)'},
    'duration':{d:'',p:'Audio(clip)'},
    'dwt':{d:'',p:'(Lst||Mtrx)(data),[opts]'},
    'e':{d:''},
    'ecef2geodetic':{d:'',p:'Real(x),Real(y),Real(z)'},
    'ecm_factor':{d:'',p:'Intg(a),[Intg(B1)]'},
    'ecris':{d:'',p:'Str(s),[Intg(n)],[Real(x)],[Real(y)]'},
    'edge_connectivity':{d:'',p:'graph(G)'},
    'edges':{d:'',p:'Graph(G),[weights]'},
    'efface':{d:'',p:'NULL or Real(n)'},
    'egcd':{d:'',p:'(Poly or Lst),(Poly or Lst),[Var]',a:['gcdex']},
    'egv':{d:'',p:'Mtrx',a:['eigenvectors','eigenvects','eigVc']},
    'egvl':{d:'',p:'Mtrx(A)',a:['eigVl']},
    'eigenvals':{d:'',p:'Mtrx',a:['eigenvalues']},
    'element':{d:'',p:'(Curve or Real_interval),[Val]'},
    'elif':{d:''},
    'eliminate':{d:'',p:'LstEq(eqs),LstVar(vars)'},
    'ellipse':{d:'',p:'Pnt(F1),Pnt(F2),(Pnt(M) or Real(a))'},
    'else':{d:''},
    'emd':{d:'',p:'Lst(data),[opts]'},
    'end':{d:'',a:['end_for','fpour','end_while','ftantque','end_if','fi','fsi','od','ffaire','ffonction','ffunction']},
    'enumerate':{d:'',p:'Lst(l),[Intg(start)]'},
    'envelope':{d:'',p:'Expr(Xpr),Var(t)||[x,y,t]'},
    'epsilon':{d:'',p:'NULL'},
    'epsilon2zero':{d:'',p:'Expr'},
    'equal':{d:'',p:'Expr,Expr'},
    'equal2diff':{d:'',p:'Equal'},
    'equal2list':{d:'',p:'Equal'},
    'equation':{d:'',p:'GeoObj, VectParam'},
    'equilateral_triangle':{d:'',p:'(Pnt(A) or Cplx),(Pnt(B) or Cplx),[Pnt(P)],[Var(C)]'},
    'erase':{d:'',p:'NULL'},
    'erase3d':{d:'',p:'NULL'},
    'erf':{d:'',p:'Real(x0)'},
    'erfc':{d:'',p:'Real(x0)'},
    'error':{d:'',p:'Str',a:['ERROR','throw']},
    'euler':{d:'',p:'Intg(n)',a:['Phi']},
    'euler_gamma':{d:''},
    'euler_lagrange':{d:'',p:'Expr(f),[(Var(x),[Var||Lst(y)]) || y(x) || Lst(y(x))]'},
    'eval':{d:'',p:'Expr',a:['evalm']},
    'eval_level':{d:'',p:'[Intg(n)]'},
    'evalb':{d:'',p:'Expr'},
    'evalc':{d:'',p:'Expr'},
    'evalf':{d:'',p:'Expr,[Int]',a:['approx']},
    'even':{d:'',p:'Intg(n)'},
    'evolute':{d:'',p:'Curve'},
    'exbisector':{d:'',p:'(Pnt(A) or Cplx),(Pnt(B) or Cplx),(Pnt(C) or Cplx)'},
    'excenter':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),(Pnt or Cplx)'},
    'excircle':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),(Pnt or Cplx)'},
    'exp':{d:'',p:'Expr or Opt',a:['EXP']},
    'exp2list':{d:'',p:'Expr'},
    'exp2pow':{d:'',p:'Expr'},
    'exp2trig':{d:'',p:'Expr'},
    'expand':{d:'',p:'Expr',a:['fdistrib','developper']},
    'expexpand':{d:'',p:'Expr'},
    'expln':{d:'',p:'Opt'},
    'exponential':{d:'',p:'Real(lambda),Real(x)',a:['exponentiald']},
    'exponential_cdf':{d:'',p:'Real(lambda),Real(x0),[Real(y0)]',a:['exponentiald_cdf']},
    'exponential_icdf':{d:'',p:'Real(lambda),Real(x0),Real(p)',a:['exponentiald_icdf']},
    'exponential_regression':{d:'',p:'Lst||Mtrx(A),[Lst]'},
    'exponential_regression_plot':{d:'',p:'Lst||Mtrx(A),[Lst]'},
    'export_graph':{d:'',p:'Graph(G),Str("filename"),[opts]'},
    'export_mathml':{d:'',p:'Expr,[display||content]'},
    'expr':{d:'',p:'Str',a:['execute']},
    'extract_measure':{d:'',p:'Var'},
    'extrema':{d:''},
    'ezgcd':{d:'',p:'Poly,Poly'},
    'f2nd':{d:'',p:'Frac or RatFrac',a:['fxnd']},
    'fMax':{d:'',p:'Expr,[Var]'},
    'fMin':{d:'',p:'Expr,[Var]'},
    'fPart':{d:'',p:'Real||LstReal',a:['frac']},
    'faces':{d:'',p:'Polygon or Polyedr(P)'},
    'factor':{d:'',p:'Expr',a:['factoriser']},
    'factor_xn':{d:'',p:'Poly(P)'},
    'factorial':{d:'',p:'Intg(n)|| Real(a)'},
    'factors':{d:'',p:'Poly or LstPoly'},
    'fadeev':{d:'',p:'Opt'},
    'false':{d:'',a:['FALSE','False']},
    'fclose':{d:'',p:'File(f)',a:['close']},
    'fcoeff':{d:'',p:'Lst(root||pole,order)'},
    'feuille':{d:'',p:'Op or Fnc',a:['op']},
    'fft':{d:'',p:'Vect or (Vect(L),Intg(a),Intg(p)'},
    'filled':{d:'',p:'Opt'},
    'filled_1':{d:'',p:'Opt'},
    'filled_2':{d:'',p:'Opt'},
    'filled_3':{d:'',p:'Opt'},
    'filled_4':{d:'',p:'Opt'},
    'filled_5':{d:'',p:'Opt'},
    'fin_enregistrement':{d:'',p:'Str(nom_de_fichier)'},
    'find':{d:'',p:'Expr,Vect'},
    'find_cliques':{d:'',p:'Graph(G),[Intg(k)||Intrv(m..n)]'},
    'find_cycles':{d:'',p:'Graph(G,[length=k||l..u])'},
    'find_minimum':{d:'',p:'(Expr||Func)(f),Real(a),Real(b),[Real(eps),Intg(maxiter)]'},
    'find_vertex_cover':{d:'',p:'Graph(G),[Intg(k)]'},
    'findhelp':{d:'',p:'Cmd',a:['?']},
    'fisher':{d:'',p:'Intg(n),Intg(m),Real(x0)',a:['snedecor','fisherd','snedecord']},
    'fisher_cdf':{d:'',p:'Intg(n),Intg(m),Real(x0)',a:['snedecor_cdf','fisherd_cdf','snedecord_cdf']},
    'fisher_icdf':{d:'',p:'Intg(n),Intg(m),Real(p)',a:['snedecor_icdf','fisherd_icdf','snedecord_icdf']},
    'fitdistr':{d:'',p:'Lst(L),Fnc(D)'},
    'fitpoly':{d:'',p:'Expr||Mtrx||Seq(Lst(x),Lst(y)),[Var[=Real(a)..Real(b)]],[Options]'},
    'fitspline':{d:'',p:'Mtrx(data),(Var||Lst)(x),[opts]'},
    'flatten':{d:'',p:'Lst||Image'},
    'float2rational':{d:'',p:'Expr',a:['exact']},
    'floor':{d:'',p:'Real or Cplx'},
    'flow_polynomial':{d:'',p:'Graph(G),[Var(x)]'},
    'flower_snark':{d:'',p:'Intg(n)'},
    'fmod':{d:'',p:'Real(a),Real(b)'},
    'foldl':{d:'',p:'op,id,Seq(r1,r2,...)'},
    'foldr':{d:'',p:'op,id,Seq(r1,r2,...)'},
    'fopen':{d:'',p:'Str(s)'},
    'for':{d:''},
    'fork_timeout':{d:'',p:'Expr(f),Real(dt)'},
    'format':{d:'',p:'Real,Str("f4"||"s5"||"e6")'},
    'fourier':{d:'',p:'Expr(f(x)),[Var(x),[Var(s)]]'},
    'fourier_an':{d:'',p:'Expr(f(x)),Var(x),Period(T),Intg(n),Real(a)'},
    'fourier_bn':{d:'',p:'Expr(f(x)),Var(x),Period(T),Intg(n),Real(a)'},
    'fourier_cn':{d:'',p:'Expr(f(x)),Var(x),Period(T),Intg(n),Real(a)'},
    'fprint':{d:'',p:'File(f),Var,[Var,Var...]'},
    'fracmod':{d:'',p:'Expr(Xpr),Intg(n)',a:['iratrecon']},
    'frame_2d':{d:'',p:'NULL'},
    'frame_3d':{d:'',p:'NULL'},
    'frames':{d:'',p:'Opt',a:['trames']},
    'frank_wolfe':{d:'',p:'Expr(f),Mtrx(A),[opts]'},
    'frenet':{d:'',p:'[X(t),Y(t)],t,[t0]'},
    'frequencies':{d:'',p:'Lst'},
    'frobenius_norm':{d:'',p:'Mtrx'},
    'froot':{d:'',p:'RatPoly(F)'},
    'fsolve':{d:'',p:'Expr,Var,[Guess or Interval],[Method]'},
    'function':{d:'',p:'Fnc(f)',a:['fonction']},
    'function_diff':{d:'',p:'Fnc(f)',a:['fonction_derivee']},
    'fundamental_cycle':{d:'',p:'Graph(G)'},
    'gammad':{d:'',p:'Real(a>0),Real(b>0),Real(x>=0)'},
    'gammad_cdf':{d:'',p:'Real(a>0),Real(b>0),Real(x0>=0),[Real(y0>=0)]'},
    'gammad_icdf':{d:'',p:'Real(a>0),Real(b>0),Real(0<=p<=1)'},
    'gauss':{d:'',p:'Expr,VectVar'},
    'gauss_seidel_linsolve':{d:'',p:'[Real(omega)],Mtrx(A),Vect(b),Real(eps),[Int(maxiter)]'},
    'gaussian_window':{d:'',p:'Lst,[Real(a)],[Interval(n1..n2)]'},
    'gaussquad':{d:'',p:'Expr(f(x)),Var(x),Real(a),Real(b)'},
    'gbasis':{d:'',p:'LstPoly,LstVar,[order]'},
    'gbasis_max_pairs':{d:'',p:'Intg'},
    'gbasis_reinject':{d:'',p:'Real(a),[Real(b)]'},
    'gbasis_simult_primes':{d:'',p:'Intg'},
    'gbasis_vars':{d:'',p:'List'},
    'gcd':{d:'',p:'(Intg(a) or Poly),(Intg(b) or Poly)',a:['igcd']},
    'genpoly':{d:'',p:'Poly(P),Intg(b),Var'},
    'geodetic2ecef':{d:'',p:'Real(latitude),Real(longitude),Real(height)'},
    'geometric':{d:'',p:'Real(p),Intg(k)'},
    'geometric_cdf':{d:'',p:'Real(p),Intg(k),[Intg(m)]'},
    'geometric_icdf':{d:'',p:'Real(p),Real(x)'},
    'getDenom':{d:'',p:'Expr'},
    'getKey':{d:'',p:'NULL'},
    'getNum':{d:'',p:'Expr'},
    'getType':{d:'',p:'Expr'},
    'get_edge_attribute':{d:'',p:'Graph(G),Edge(e),Seq(tag1=value1,tag2=value2,..)'},
    'get_edge_weight':{d:'',p:'Graph(G),Edge(e)'},
    'get_graph_attribute':{d:'',p:'Graph(G),Seq(tag1=value1,tag2=value2,..)'},
    'get_vertex_attribute':{d:'',p:'Graph(G),Vrtx(v),Seq(tag1=value1,tag2=value2,..)'},
    'girth':{d:'',p:'Graph(G)'},
    'gl_ortho':{d:'',p:'Opt=Interval'},
    'gl_quaternion':{d:'',p:'Opt=Lst'},
    'gl_rotation':{d:'',p:'Opt=NameFich'},
    'gl_showaxes':{d:'',p:'Opt=Boolean'},
    'gl_shownames':{d:'',p:'Opt=Boolean'},
    'gl_texture':{d:'',p:'Opt=NameFich'},
    'gl_x':{d:'',p:'Opt=Interval',a:['gl_y','gl_z']},
    'gl_x_axis_color':{d:'',p:'Opt=Intg',a:['gl_y_axis_color','gl_z_axis_color']},
    'gl_x_axis_name':{d:'',p:'Opt=Str',a:['gl_y_axis_name','gl_z_axis_name']},
    'gl_x_axis_unit':{d:'',p:'Opt=Str',a:['gl_y_axis_unit','gl_z_axis_unit']},
    'gl_xtick':{d:'',p:'Opt=Real',a:['gl_ytick','gl_ztick']},
    'gnuplot':{d:'',p:'Str'},
    'goldberg_snark':{d:'',p:'Intg(n)'},
    'goto':{d:'',p:'Var(nom)'},
    'grad':{d:'',p:'Expr(Xpr),LstVar'},
    'gramschmidt':{d:'',p:'Basis(B),ScalarProd(Sp)'},
    'graph':{d:'',p:'[Lst(V)],[Set(E)],[Mtrx(A)],[options]'},
    'graph2tex':{d:'',p:'[Str("filename")]'},
    'graph3d2tex':{d:'',p:'[Str"filename")]'},
    'graph_automorphisms':{d:'',p:'Graph(G)'},
    'graph_charpoly':{d:'',p:'Graph(G),[Var(x)]'},
    'graph_complement':{d:'',p:'Graph(G)'},
    'graph_diameter':{d:'',p:'Graph(G)'},
    'graph_equal':{d:'',p:'Graph(G1),Graph(G2)'},
    'graph_join':{d:'',p:'Graph(G),Graph(H)'},
    'graph_power':{d:'',p:'Graph(G),Intg(k)'},
    'graph_rank':{d:'',p:'Graph(G),[Lst(E)]'},
    'graph_spectrum':{d:'',p:'Graph(G)'},
    'graph_union':{d:'',p:'Seq(G1,G2,...)'},
    'graph_vertices':{d:'',p:'Graph(G)'},
    'greduce':{d:'',p:'Poly,LstPoly,LstVar,[order]'},
    'greedy_clique':{d:'',p:'Graph(G),[Intg(n)]'},
    'greedy_color':{d:'',p:'Graph(G),[Permu(p)]'},
    'greedy_independent_set':{d:'',p:'Graph(G),[Intg(n)]'},
    'grid_graph':{d:'',p:'Intg(m),Intg(n),[triangle]'},
    'grid_paper':{d:'',p:'Real(ux),Real(t),Real(uy),[x=xmin..xmax,y=ymin..ymax]'},
    'groupermu':{d:'',p:'Permut(a),Permut(b)'},
    'haar_graph':{d:'',p:'Intg(n)'},
    'hadamard':{d:'',p:'Mtrx,Mtrx'},
    'half_cone':{d:'',p:'Pnt(A),Vect(v),Real(t),[Real(h)]'},
    'half_line':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx)'},
    'halftan':{d:'',p:'Expr'},
    'halftan_hyp2exp':{d:'',p:'ExprTrig'},
    'halt':{d:'',p:'NULL'},
    'hamdist':{d:'',p:'Intg,Intg'},
    'hamming':{d:'',p:'Str(s1)||Lst(s1),Str(s2)||Lst(s2)'},
    'hamming_window':{d:'',p:'Lst,[Interval(n1..n2)]'},
    'hann_poisson_window':{d:'',p:'Lst,[Interval(n1..n2)]'},
    'hann_window':{d:'',p:'Lst,[Interval(n1..n2)]'},
    'harmonic_centrality':{d:'',p:'Graph(G),[Vrtx(v)]'},
    'harmonic_conjugate':{d:'',p:'Line or Pnt(A),Line or Pnt(B),Line or Pnt(C)'},
    'harmonic_division':{d:'',p:'Pnt or Line,Pnt or Line,Pnt or Line,Var'},
    'has':{d:'',p:'Expr,Var'},
    'has_arc':{d:'',p:'Graph(G),Edge(e)'},
    'has_edge':{d:'',p:'Graph(G),Edge(e)'},
    'hasard':{d:'',p:'Intg(n) or Interval(p..n) or NULL,[Intg(b1) or Lst(L)],[Intg(b2)]'},
    'head':{d:'',p:'Vect or Seq or Str'},
    'heapify':{d:'',p:'List'},
    'heappop':{d:'',p:'List'},
    'heappush':{d:'',p:'List,Object'},
    'hermite':{d:'',p:'Intg(n)||Matr(A)'},
    'hessenberg':{d:'',p:'Mtrx(A),[Intg(n)]'},
    'hessian':{d:'',p:'Expr(Xpr),LstVar'},
    'heugcd':{d:'',p:'Poly,Poly'},
    'hexagon':{d:'',p:'Pnt(A)||Cplx,Pnt(B)||Cplx,[Pnt(P)],[Var(C)],[Var(D)],[Var(E)],[Var(F)]'},
    'hht':{d:'',p:'Lst(data)||Mtrx(imf),[opts]'},
    'hidden_name':{d:'',p:'Opt'},
    'highlight_edges':{d:'',p:'Graph(G),Edge(e)||Lst(E),[Color(c)||Lst(C)]'},
    'highlight_subgraph':{d:'',p:'Graph(G),Graph(S)||Lst(S1,S2,..),Seq(c1,c2)'},
    'highlight_trail':{d:'',p:'Graph(G),Trail(t)||Lst(T),[Color(c)||Lst(C)]'},
    'highlight_vertex':{d:'',p:'Graph(G),Vrtx(v)||Lst(V),[Color(c)||Lst(C)]'},
    'highpass':{d:'',p:'Lst(s),Real(c),[Intg(samplerate)]'},
    'hilbert':{d:'',p:'Intg(n)||(Expr(f),[Var(x)])||Lst(u)'},
    'histogram':{d:'',p:'Lst(data),[Lst(eff) || Intg(nc) || Real(classmin)],[Real(classsize)]'},
    'homogeneize':{d:'',p:'Expr(P),[Var(t)]'},
    'homothety':{d:'',p:'Pnt(C),Real(k),Pnt(A)'},
    'horner':{d:'',p:'Poly(P),Real(a)'},
    'hsv':{d:'',p:'Lst(h,s,v)||Color(c)'},
    'hsv2rgb':{d:'',p:'Lst(h,s,v)'},
    'hyp2exp':{d:'',p:'ExprHyperb'},
    'hyperbola':{d:'',p:'Focus(F1),Focus(F2),(Pnt(M) or Real(a))'},
    'hypercube_graph':{d:'',p:'Intg(n)'},
    'i':{d:''},
    'iPart':{d:'',p:'Real||LstReal'},
    'i[]':{d:'',p:'Seq(a,b)',a:['[..]']},
    'iabcuv':{d:'',p:'Intg(a),Intg(b),Intg(c)'},
    'ibasis':{d:'',p:'Lst(Vect,..,Vect),Lst(Vect,..,Vect)'},
    'ibpdv':{d:'',p:'Expr(f(x)),Expr(v(x)),[Var(x)],[Real(a)],[Real(b)]'},
    'ibpu':{d:'',p:'Expr(f(x)),Expr(u(x)),[Var(x)],[Real(a)],[Real(b)]'},
    'icdf':{d:'',p:'Func,FuncParams'},
    'ichinrem':{d:'',p:'LstIntg(a,p),LstIntg(b,q)',a:['ichrem']},
    'icomp':{d:'',p:'Intg(n),Intg(k),[zeros=true||false]'},
    'icontent':{d:'',p:'Poly,[Var]'},
    'icosahedron':{d:'',p:'Pnt(A),Pnt(B),Pnt(C)'},
    'id':{d:'',p:'Seq'},
    'identify_graph':{d:'',p:'Graph(G)'},
    'identity':{d:'',p:'Intg(n)',a:['idn']},
    'idivis':{d:'',p:'Intg(a) or LstIntg',a:['divisors']},
    'idwt':{d:'',p:'(Lst||Mtrx)(T),[opts]'},
    'iegcd':{d:'',p:'Intg,Intg',a:['igcdex','bezout_entiers']},
    'if':{d:''},
    'ifactor':{d:'',p:'Intg(a)',a:['factoriser_entier']},
    'ifactors':{d:'',p:'Intg(a) or LstIntg',a:['facteurs_premiers']},
    'ifft':{d:'',p:'Vect'},
    'ifourier':{d:'',p:'Expr(F(s)),[Var(s),[Var(x)]]'},
    'ifte':{d:'',p:'Cond,Expr1,Expr2',a:['IFTE']},
    'igamma':{d:'',p:'Real(a),Real(x),[1]'},
    'ihermite':{d:'',p:'Mtrx(A)'},
    'ilaplace':{d:'',p:'Expr,[Var],[IlapVar]',a:['invlaplace']},
    'im':{d:'',p:'Cplx',a:['imag']},
    'image':{d:'',p:'Mtrx(M)||Strng(imgfname)'},
    'imfplot':{d:'',p:'Lst(imf),[opts]',a:['plotimf']},
    'implicitdiff':{d:'',p:'constr,[depvars],y,diffvars'},
    'import_graph':{d:'',p:'Str("filename"),[opts]'},
    'in':{d:''},
    'inString':{d:'',p:'Str(l),Elem(e)'},
    'in_ideal':{d:'',p:'Poly,Lst,LstVar,[order]'},
    'incenter':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),(Pnt or Cplx)'},
    'incidence_matrix':{d:'',p:'Graph(G)'},
    'incident_edges':{d:'',p:'Graph(G),Vrtx(v)'},
    'incircle':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),(Pnt or Cplx)'},
    'increasing_power':{d:'',p:':=Intg(0 or 1)'},
    'independence_number':{d:'',p:'Graph(G)'},
    'index':{d:'',p:'Vect,Expr'},
    'induced_subgraph':{d:'',p:'Graph(G),Lst(V)'},
    'inertia':{d:'',p:'Mtrx(A),[B,[p0]]'},
    'infinity':{d:''},
    'information_centrality':{d:'',p:'Graph(G),[Vrtx(v)],[approx]'},
    'input':{d:'',p:'[Str],Var(Var)',a:['Input','lis']},
    'inputform':{d:'',p:'[Str],Var,[Str],[Var],[Str],[Var]'},
    'insert':{d:'',p:'Vect(l)||Str(l),Intg(n),Val(b)'},
    'insmod':{d:'',p:'Str(pwd)'},
    'instfreq':{d:'',p:'Vect(u)||Expr(u),[Var(x)]'},
    'instphase':{d:'',p:'Vect(u)||Expr(u),[Var(x)]'},
    'int':{d:'',p:'Expr,[Var(x)],[Real(a)],[Real(b)]',a:['integrate','integrer']},
    'inter':{d:'',p:'Curve,Curve,[Pnt|Lst]'},
    'interactive_plotode':{d:'',p:'Expr,VectVar',a:['interactive_odeplot']},
    'interp':{d:'',p:'Lst(colors)||Seq(Image(A),Image(B)||Color(c))||Seq(Lst(x0),Lst(y0),Lst(x))||Seq(Lst(x),Lst(y))'},
    'intersect':{d:'',p:'(Vect or Set),(Vect or Set)'},
    'interval':{d:'',p:'Opt'},
    'interval2center':{d:'',p:'Interval or Real'},
    'interval_graph':{d:'',p:'Seq||Lst(a..b,c..d,...)'},
    'inv':{d:'',p:'Expr||Mtrx||Image||Audio',a:['inverse']},
    'inversion':{d:'',p:'Pnt(C),Real(k),Pnt(A)'},
    'invztrans':{d:'',p:'Expr,[Var],[InvZtransVar]'},
    'iquo':{d:'',p:'Intg(a),Intg(b)',a:['intDiv']},
    'iquorem':{d:'',p:'Intg(a),Intg(b)',a:['divmod']},
    'irem':{d:'',p:'Intg(a),Intg(b)',a:['remain']},
    'is_acyclic':{d:'',p:'Graph(G)'},
    'is_arborescence':{d:'',p:'Graph(G)'},
    'is_biconnected':{d:'',p:'Graph(G)'},
    'is_bipartite':{d:'',p:'Graph(G),[Var(P)]'},
    'is_clique':{d:'',p:'Graph(G)'},
    'is_collinear':{d:'',p:'LstPnt'},
    'is_concyclic':{d:'',p:'LstPnt'},
    'is_conjugate':{d:'',p:'Crcle||Line,Pnt||Line,Pnt||Line,[Pnt||Line]'},
    'is_connected':{d:'',p:'Graph(G)'},
    'is_coplanar':{d:'',p:'Pnt,Pnt,Pnt,Pnt'},
    'is_cospherical':{d:'',p:'Pnt,Pnt,Pnt,Pnt'},
    'is_cut_set':{d:'',p:'Graph(G),Lst(E)'},
    'is_cycle':{d:'',p:'Lst'},
    'is_directed':{d:'',p:'Graph(G)'},
    'is_element':{d:'',p:'Pnt,GeoObj'},
    'is_equilateral':{d:'',p:'Pnt||Cplx,Pnt||Cplx,Pnt||Cplx'},
    'is_eulerian':{d:'',p:'Graph(G),[Var(T)]'},
    'is_forest':{d:'',p:'Graph(G)'},
    'is_graphic_sequence':{d:'',p:'Lst(L)'},
    'is_hamiltonian':{d:'',p:'Graph(G),[Var(hc)]'},
    'is_harmonic':{d:'',p:'Pnt or Cplx,Pnt or Cplx,Pnt or Cplx,Pnt or Cplx'},
    'is_harmonic_circle_bundle':{d:'',p:'Lst(Crcle)'},
    'is_harmonic_line_bundle':{d:'',p:'Lst(Line)'},
    'is_included':{d:'',p:'Lst||Ens,Lst||Ens'},
    'is_inside':{d:'',p:'Pnt,Polygon or Circle'},
    'is_integer_graph':{d:'',p:'Graph(G)'},
    'is_irreducible':{d:'',p:'Polynomial'},
    'is_isomorphic':{d:'',p:'Graph(G1),Graph(G2),[Var(I)]'},
    'is_isosceles':{d:'',p:'Pnt or Cplx,Pnt or Cplx,Pnt or Cplx'},
    'is_network':{d:'',p:'Graph(G),[Vrtx(s),Vrtx(t)]'},
    'is_orthogonal':{d:'',p:'Line||Crcle,Line||Crcle'},
    'is_parallel':{d:'',p:'Line or Plan ,Line or Plan'},
    'is_parallelogram':{d:'',p:'Pnt or Cplx,Pnt or Cplx,Pnt or Cplx,Pnt or Cplx'},
    'is_permu':{d:'',p:'Lst',a:['est_permu']},
    'is_perpendicular':{d:'',p:'Line or Plan,Line or Plan'},
    'is_planar':{d:'',p:'Graph(G)'},
    'is_prime':{d:'',p:'Intg,[1 || 2]'},
    'is_pseudoprime':{d:'',p:'Intg'},
    'is_reachable':{d:'',p:'Graph(G),Vrtx(u),Vrtx(v)'},
    'is_rectangle':{d:'',p:'Pnt||Cplx,Pnt||Cplx,Pnt||Cplx,[Pnt||Cplx]'},
    'is_regular':{d:'',p:'Graph(G)'},
    'is_rhombus':{d:'',p:'Pnt or Cplx,Pnt or Cplx,Pnt or Cplx,Pnt or Cplx'},
    'is_split_graph':{d:'',p:'Graph(G),[part]'},
    'is_square':{d:'',p:'Pnt,Pnt,Pnt,Pnt'},
    'is_strongly_connected':{d:'',p:'Graph(G)'},
    'is_strongly_regular':{d:'',p:'Graph(G),[Var(srg)]'},
    'is_subgraph_isomorphic':{d:'',p:'Graph(G1),Graph(G2),[opts]'},
    'is_tournament':{d:'',p:'Graph(G)'},
    'is_tree':{d:'',p:'Graph(G)'},
    'is_triconnected':{d:'',p:'Graph(G)'},
    'is_two_edge_connected':{d:'',p:'Graph(G)'},
    'is_vertex_colorable':{d:'',p:'Graph(G),Intg(k),[Var(col)]'},
    'is_weighted':{d:'',p:'Graph(G)'},
    'isinf':{d:'',p:'Expr'},
    'ismith':{d:'',p:'Mtrx(A)'},
    'isnan':{d:'',p:'Expr'},
    'isobarycenter':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),(Pnt or Cplx)'},
    'isolve':{d:'',p:'Eqn||List(Eqn),[Intg(n)||(Idnt(Z1),Idnt(Z2),...)]'},
    'isom':{d:'',p:'Mtrx'},
    'isomorphic_copy':{d:'',p:'Graph(G),Permu(sigma)'},
    'isopolygon':{d:'',p:'Pnt,Pnt,[Pnt],Intg(n)'},
    'isosceles_triangle':{d:'',p:'(Pnt(A) or Cplx),(Pnt(B) or Cplx),(Angle(t) or Pnt(P) or Lst(P,t)),[Var(C)]'},
    'isposdef':{d:'',p:'Mtrx(A)'},
    'isprime':{d:'',p:'Intg(a)',a:['isPrime']},
    'istft':{d:'',p:'Mtrx(data)'},
    'ithprime':{d:'',p:'Intg(n)'},
    'jacobi_equation':{d:'',p:'Expr(f),Var(x),Var(y),Expr(y0),Var(h),Real(a)'},
    'jacobi_linsolve':{d:'',p:'Mtrx(A),Vect(b),Real(eps),[Int(maxiter)]'},
    'jacobi_symbol':{d:'',p:'Intg,Intg'},
    'johnson_graph':{d:'',p:'Intg(n),Intg(k)'},
    'join':{d:'',p:'Str(sep),Lst(strlst)'},
    'jordan':{d:'',p:'Mtrx'},
    'jusque':{d:'',a:['to']},
    'katz_centrality':{d:'',p:'Graph(G),Real(alpha),[Vrtx(v)]'},
    'keep_algext':{d:'',p:':=Intg(0 or 1)'},
    'keep_pivot':{d:'',p:'Opt'},
    'ker':{d:'',p:'Mtrx',a:['kernel','nullspace']},
    'kernel_density':{d:'',p:'Lst(L),[options]',a:['kde']},
    'kill':{d:'',p:'NULL',a:['tuer']},
    'kmeans':{d:'',p:'Mtrx||Lst(data),[opts]'},
    'kneser_graph':{d:'',p:'Intg(n),Intg(k)'},
    'kolmogorovd':{d:'',p:'Real(x)'},
    'kolmogorovt':{d:'',p:'Lst(l1),Lst(l2) || DistribLaw(s)'},
    'kovacicsols':{d:'',p:'Expr||Lst(eq),[Var(x),[Var(y)]]'},
    'kspaths':{d:'',p:'Graph(G),Vrtx(s),Vrtx(t),Intg(k)'},
    'l1norm':{d:'',p:'Vect'},
    'label':{d:'',p:'Var(nom)'},
    'labels':{d:'',p:'Cplx or Lst,Str'},
    'lagrange':{d:'',p:'(Lst_xk,Lst_yk)||Mtrx_2*n||(Lst_xk,Fnc(f)),[Var||[]||lagrange]'},
    'laguerre':{d:'',p:'Intg(n)'},
    'laplace':{d:'',p:'Expr,[Var],[LapVar]'},
    'laplacian':{d:'',p:'Expr(Xpr),LstVar'},
    'laplacian_matrix':{d:'',p:'Graph(G),[normal]'},
    'latex':{d:'',p:'Expr',a:['TeX']},
    'lcf_graph':{d:'',p:'Lst(J),[Intg(k)]'},
    'lcm':{d:'',p:'(Intg or Poly),(Intg or Poly)'},
    'lcoeff':{d:'',p:'Poly||Lst'},
    'ldl':{d:'',p:'Mtrx(A),[opts]'},
    'left':{d:'',p:'Equal(a=b) or Interval(a..b) or Str,Intg',a:['lhs','gauche']},
    'legend':{d:'',p:'Cplx or Lst,Str'},
    'legendre':{d:'',p:'Intg(n)'},
    'legendre_symbol':{d:'',p:'Intg,Intg'},
    'leve_crayon':{d:'',p:'NULL',a:['penup']},
    'levenshtein':{d:'',p:'Str(s1)||Lst(s1),Str(s2)||Lst(s2)'},
    'lgcd':{d:'',p:'Seq or Lst'},
    'limit':{d:'',p:'Expr,Var,Val,[Dir(d)]',a:['limite']},
    'lin':{d:'',p:'Expr',a:['lineariser']},
    'linabs':{d:'',p:'Expr,[Var]'},
    'line':{d:'',p:'Pnt||Cplx||Eq,[Pnt||slope||Var]'},
    'line_graph':{d:'',p:'Graph(G)'},
    'line_paper':{d:'',p:'Real(ux),Real(t),[x=xmin..xmax,y=ymin..ymax]'},
    'line_segments':{d:'',p:'Polygon or Polyedr(P)'},
    'line_width_1':{d:'',p:'Opt',a:['line_width_2','line_width_3','line_width_4','line_width_5','line_width_6','line_width_7','epaisseur_ligne_1','epaisseur_ligne_2','epaisseur_ligne_3','epaisseur_ligne_4','epaisseur_ligne_5','epaisseur_ligne_6','epaisseur_ligne_7']},
    'linear_interpolate':{d:'',p:'Mtrx,xmin,xmax,xstep'},
    'linear_regression':{d:'',p:'Lst||Mtrx(A),[Lst]'},
    'linear_regression_plot':{d:'',p:'Lst||Mtrx(A),[Lst]'},
    'linfnorm':{d:'',p:'Mtrx'},
    'linsolve':{d:'',p:'LstLinEq,LstVar',a:['resoudre_systeme_lineaire']},
    'linspace':{d:'',p:'Real(a),Real(b),[Int(n)]'},
    'linstep':{d:'',p:'Expr,[Var]'},
    'list':{d:'',p:'Opt'},
    'list2exp':{d:'',p:'List'},
    'list2mat':{d:'',p:'Lst(l),Intg(n)'},
    'list_edge_attributes':{d:'',p:'Graph(G),Edge(e)'},
    'list_graph_attributes':{d:'',p:'Graph(G)'},
    'list_vertex_attributes':{d:'',p:'Graph(G),Vrtx(v)'},
    'listplot':{d:'',p:'Lst(l)||Mtrx(M)',a:['plotlist']},
    'lll':{d:'',p:'Mtrx'},
    'ln':{d:'',p:'Expr or Opt',a:['log','LN']},
    'lname':{d:'',p:'Expr',a:['indets']},
    'lncollect':{d:'',p:'Expr'},
    'lnexpand':{d:'',p:'Expr'},
    'local':{d:'',a:['var']},
    'locus':{d:'',p:'Pnt,Elem'},
    'log10':{d:'',p:'Expr'},
    'log2':{d:'',p:'Expr'},
    'logarithmic_regression':{d:'',p:'Lst||Mtrx(A),[Lst]'},
    'logarithmic_regression_plot':{d:'',p:'Lst||Mtrx(A),[Lst]'},
    'logb':{d:'',p:'Real,Real'},
    'logistic':{d:'',p:'Real(x),[Real(x0),[Real(L),[Real(k)]]]'},
    'logistic_regression':{d:'',p:'Lst(L),Real(x0),Real(y0)'},
    'logistic_regression_plot':{d:'',p:'Lst(L),Real(x0),Real(y0)'},
    'lower':{d:'',p:'Mtrx||Strng'},
    'lowest_common_ancestor':{d:'',p:'Graph(T),Vrtx(r),Seq(u,v)||Lst([u1,v1],[u2,v2],...)'},
    'lowpass':{d:'',p:'Lst(s),Real(c),[Intg(samplerate)]'},
    'lp_assume':{d:'',p:'Opt',a:['lp_binary','lp_binaryvariables','lp_depthlimit','lp_integer','lp_integervariables','lp_maximize','lp_nonnegative','lp_nonnegint','lp_nodelimit','lp_method','lp_simplex','lp_interiorpoint','lp_maxcuts','lp_gaptolerance','lp_nodeselect','lp_varselect','lp_firstfractional','lp_lastfractional','lp_mostfractional','lp_pseudocost','lp_depthfirst','lp_breadthfirst','lp_bestlocalbound','lp_bestprojection','lp_hybrid','lp_iterationlimit','lp_timelimit','lp_verbose','lp_presolve','lp_heuristic','lp_nonnegint','nonnegint']},
    'lpsolve':{d:'',p:'Expr(o),[List(c)],[bounds],[options]'},
    'lsmod':{d:'',p:'NULL'},
    'lu':{d:'',p:'Mtrx'},
    'lvar':{d:'',p:'Expr'},
    'mRow':{d:'',p:'Expr(Xpr),Mtrx(A),Intg(n1)'},
    'mRowAdd':{d:'',p:'Expr(Xpr),Mtrx(A),Intg(n1),Intg(n2)'},
    'make_directed':{d:'',p:'Graph(G),[Mrtx(A)]'},
    'make_weighted':{d:'',p:'Graph(G),[Mrtx(M)]'},
    'makelist':{d:'',p:'Fnc,InitVal,FinalVal,StepVal'},
    'makemat':{d:'',p:'Fnct(f),RowsNumb,ColsNumb'},
    'makesuite':{d:'',p:'Vect||Lst'},
    'makevector':{d:'',p:'Seq'},
    'map':{d:'',p:'Lst(l),Fnc(f)'},
    'maple2mupad':{d:'',p:'Str("Name_Maplefile"),Str("Name_Mupadfile")'},
    'maple2xcas':{d:'',p:'Str("NameMapleFile"),Str("NameXcasFile")'},
    'maple_ifactors':{d:'',p:'Intg(n)'},
    'markov':{d:'',p:'Mtrx(M),[Real(eps)]'},
    'mat2list':{d:'',p:'Mtrx'},
    'mathml':{d:'',p:'Expr'},
    'matpow':{d:'',p:'Mtrx,Intg(n)'},
    'matrix':{d:'',p:'Intg(p),Intg(q),(Fnc(f) or Val(a))'},
    'matrix_norm':{d:'',p:'Mtrx,[2]||[inf]'},
    'max':{d:'',p:'Seq||Lst'},
    'maxflow':{d:'',p:'Graph(G),Vrtx(s),Vrtx(t)'},
    'maximal_independent_set':{d:'',p:'Graph(G)'},
    'maximize':{d:'',p:'Expr,[Constr],Vars,[Options]'},
    'maximum_clique':{d:'',p:'Graph(G)'},
    'maximum_degree':{d:'',p:'Graph(G)'},
    'maximum_independent_set':{d:'',p:'Graph(G)'},
    'maximum_matching':{d:'',p:'Graph(G)'},
    'maxnorm':{d:'',p:'Vect or Mtrx'},
    'mean':{d:'',p:'Lst||Mtrx,[Lst]',a:['moyenne']},
    'median':{d:'',p:'Lst||Mtrx,[Lst]'},
    'median_line':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),(Pnt or Cplx)'},
    'member':{d:'',p:'Elem(e),(Lst(l) or Set(l))'},
    'mgf':{d:'',p:'Func,[Real(Param_1),Real(Param_2)]'},
    'mid':{d:'',p:'Lst(l) or Str(l),Intg(d),Intg(n)'},
    'midpoint':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx)'},
    'min':{d:'',p:'Seq||Lst'},
    'minimal_edge_coloring':{d:'',p:'Graph(G),[sto]'},
    'minimal_spanning_tree':{d:'',p:'Graph(G)'},
    'minimal_vertex_coloring':{d:'',p:'Graph(G),[sto]'},
    'minimax':{d:'',p:'Expr,Var=Real(a)..Real(b),Intg(n)||Lst(Intg(n),Intg(m)),[opts]'},
    'minimize':{d:'',p:'Expr,[Constr],Vars,[Options]'},
    'minimum_cut':{d:'',p:'Graph(G),Vrtx(s),Vrtx(t)'},
    'minimum_degree':{d:'',p:'Graph(G)'},
    'minimum_vertex_cover':{d:'',p:'Graph(G),[approx]'},
    'minus':{d:'',p:'(Vect or Set),(Vect or Set)'},
    'mixdown':{d:'',p:'Audio(clip1),(Real||Lst)(parm1),Audio(clip2),(Real||Lst)(parm2),...'},
    'mkisom':{d:'',p:'Vect,(Sign(1) or -1)'},
    'mksa':{d:'',p:'Unit'},
    'mod':{d:'',p:'Intg(n),Intg(p)',a:['%']},
    'modf':{d:'',p:'Real(a)'},
    'modgcd':{d:'',p:'Poly,Poly'},
    'monotonic':{d:''},
    'montre_tortue':{d:'',p:'NULL'},
    'moving_average':{d:'',p:'Lst(A),Intg(n)'},
    'moyal':{d:'',p:'Expr,Expr,VectVar'},
    'mult_c_conjugate':{d:'',p:'Expr',a:['multiplier_conjugue_complexe']},
    'mult_conjugate':{d:'',p:'Expr',a:['multiplier_conjugue']},
    'multinomial':{d:'',p:'Intg(n),Vect(p),Vect(k)'},
    'multiply':{d:'',p:'Intg or Lst, Intg or Lst'},
    'mupad2maple':{d:'',p:'Str("NameMupadFile"),Str("NameMapleFile")'},
    'mupad2xcas':{d:'',p:'Str("NameMupadFile"),Str("NameXcasFile")'},
    'mycielski':{d:'',p:'Graph(G)'},
    'nDeriv':{d:'',p:'Expr(Xpr),Var(Var),[Real(h)]'},
    'nSolve':{d:'',p:'Expr,Var,[Guess or Interval],[Method]'},
    'negbinomial':{d:'',p:'Intg(n),Intg(k),Real(p in 0..1)'},
    'negbinomial_cdf':{d:'',p:'Intg(n),Real(p),Real(x),[Real(y)]'},
    'negbinomial_icdf':{d:'',p:'Intg(n),Real(p),Real(t)'},
    'neighbors':{d:'',p:'Graph(G),[Vrtx(v)]'},
    'network_transitivity':{d:'',p:'Graph(G)'},
    'neural_network':{d:'',p:'Vect(topology)||NeuralNet(net),[opts]'},
    'newList':{d:'',p:'Intg(n)'},
    'newMat':{d:'',p:'Intg(n),Intg(p)'},
    'newton':{d:'',p:'Expr(f(x)),Var(x),[ApproxVal(a),NumIter(p)]'},
    'nextperm':{d:'',p:'Intg(n)'},
    'nextprime':{d:'',p:'Intg(a)'},
    'nlp_initialpoint':{d:'',p:'Opt',a:['nlp_iterationlimit','nlp_nonnegative','nlp_precision','nlp_maximize','nlp_presolve','nlp_method','nlp_integervariables','nlp_integer','nlp_binaryvariables','nlp_binary','nlp_tolerance','nlp_verbose','nlp_nonnegint']},
    'nlpsolve':{d:'',p:'Expr(objective),[Lst(constr)],[Seq(bd)],[Seq(opts)]'},
    'nodisp':{d:'',p:'Expr'},
    'non_recursive_normal':{d:'',p:'Expr'},
    'nop':{d:'',p:'NULL'},
    'norm':{d:'',p:'Vect or Mtrx',a:['l2norm']},
    'normal':{d:'',p:'Expr',a:['evala']},
    'normal_cdf':{d:'',p:'Real(mu),Real(sigma),Real(x0),[Real(y0)]',a:['normald_cdf']},
    'normal_icdf':{d:'',p:'Real(mu),Real(sigma),Real(p)',a:['normald_icdf']},
    'normald':{d:'',p:'Real(mu),Real(sigma),Real(x0)',a:['NORMALD']},
    'normalize':{d:'',p:'Lst||Cplx||Audio',a:['unitV']},
    'normalt':{d:'',p:'Lst,Real,[Real],Fnc,[Real]'},
    'not':{d:'',p:'Boolean',a:['non']},
    'nprimes':{d:'',p:'Intg(n)'},
    'number_of_edges':{d:'',p:'Graph(G)'},
    'number_of_spanning_trees':{d:'',p:'Graph(G)'},
    'number_of_triangles':{d:'',p:'Graph(G)'},
    'number_of_vertices':{d:'',p:'Graph(G)'},
    'numdiff':{d:'',p:'Lst(X),Lst(Y),Real(x0),[Intg(n)]'},
    'numer':{d:'',p:'Frac(a/b) or RatFrac'},
    'octahedron':{d:'',p:'Pnt(A),Pnt(B),Pnt(C)'},
    'odd':{d:'',p:'Intg(n)'},
    'odd_girth':{d:'',p:'Graph(G)'},
    'odd_graph':{d:'',p:'Intg(n)'},
    'odesolve':{d:'',p:'Expr,VectVar,VectInitCond,FinalVal,[tstep=Val,curve]'},
    'of':{d:'',p:'Fnc(f),Real(a)'},
    'open':{d:'',p:'Str(s)'},
    'open_polygon':{d:'',p:'LstPnt||LstCplx'},
    'option':{d:''},
    'or':{d:'',p:'Expr, Expr',a:['||','ou']},
    'ord':{d:'',p:'Char||LstChar'},
    'order':{d:'',p:'g'},
    'order_size':{d:'',p:'Expr'},
    'ordinate':{d:'',p:'Pnt or Vect'},
    'orthocenter':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),(Pnt or Cplx)'},
    'orthogonal':{d:'',p:'(Pnt),(Line or Plan)'},
    'osculating_circle':{d:'',p:'Curve,Point'},
    'output':{d:'',p:'[Str],Var(Var)',a:['Output']},
    'p1oc2':{d:'',p:'Permut,Cycle'},
    'p1op2':{d:'',p:'Permut,Permut'},
    'pa2b2':{d:'',p:'Intg(n)'},
    'pade':{d:'',p:'Expr(Xpr), Var(x), (Intg(n) || Poly(N)), Intg(p)'},
    'paley_graph':{d:'',p:'Intg(p),[Intg(k)]'},
    'parabola':{d:'',p:'Pnt(F)||Pnt(xA+i*yA),Pnt(A)||Real(c),[Pnt(P)]'},
    'parallel':{d:'',p:'Pnt or Line,Line or Plan,[Line]'},
    'parallelepiped':{d:'',p:'Pnt(A),Pnt(B),Pnt(C),Pnt(D)'},
    'parallelogram':{d:'',p:'Pnt(A)||Cplx,Pnt(B)||Cplx,Pnt(C)||Cplx,[Var(D)]'},
    'parameq':{d:'',p:'GeoObj'},
    'parameter':{d:''},
    'parfrac':{d:'',p:'Opt',a:['fullparfrac']},
    'pari':{d:'',p:'Str,arguments'},
    'part':{d:'',p:'Expr, Intg(n)'},
    'partfrac':{d:'',p:'RatFrac or Opt'},
    'parzen_window':{d:'',p:'Lst,[Interval(n1..n2)]'},
    'pas_de_cote':{d:'',p:'NULL or Real(n)'},
    'path_graph':{d:'',p:'Intg(n)||Lst(V)'},
    'pcar':{d:'',p:'Mtrx,[Var]',a:['charpoly']},
    'pcar_hessenberg':{d:'',p:'Mtrx,[Var]'},
    'pcoeff':{d:'',p:'Vect',a:['pcoef']},
    'perimeter':{d:'',p:'Polygone'},
    'perimeterat':{d:'',p:'Polygone, Pnt||Cplx(z0)'},
    'perimeteratraw':{d:'',p:'Polygone, Pnt||Cplx(z0)'},
    'period':{d:'',p:'Expr,[Var]'},
    'periodic':{d:'',p:'Expr,Var,Real(a),Real(b)||Expr,Var=a..b'},
    'perm':{d:'',p:'Intg(n),Intg(p)',a:['nPr']},
    'perminv':{d:'',p:'Permut(a)'},
    'permu2cycles':{d:'',p:'Permut'},
    'permu2mat':{d:'',p:'Permut(p)'},
    'permuorder':{d:'',p:'Permut(a)'},
    'permute_vertices':{d:'',p:'Graph(G),Lst(V)'},
    'perpen_bisector':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx)'},
    'perpendicular':{d:'',p:'(Pnt or Line),(Line or Plan)'},
    'petersen_graph':{d:'',p:'Intg(n),[Intg(k)]'},
    'peval':{d:'',p:'Vect,Real(x0)',a:['polyEval']},
    'pi':{d:'',a:['Pi']},
    'piecewise':{d:'',p:'Cond1,Expr1,..,Cond2p,Expr2p,[Expr2p+1]'},
    'pivot':{d:'',p:'Mtrx(A),Intg(nl),Intg(nc)'},
    'pixoff':{d:'',p:'Real(x),Real(y)'},
    'pixon':{d:'',p:'Real(x),Real(y)'},
    'planar':{d:'',p:'Opt'},
    'plane':{d:'',p:'Pnt or Eq, [Pnt or Line],[Pnt]'},
    'plane_dual':{d:'',p:'Graph(G)||Lst(F)'},
    'playsnd':{d:'',p:'Vect'},
    'plex':{d:'',p:'Opt'},
    'plot':{d:'',p:'(Expr or LstExpr),Var[=VarMin..VarMax],[color=LstColor]',a:['graphe']},
    'plot3d':{d:'',p:'Expr||Lst(3*Expr),Var,Var',a:['graphe3d']},
    'plotarea':{d:'',p:'Expr,x=a..b,[n],[Method]',a:['areaplot']},
    'plotcdf':{d:'',p:'Func,FuncParams'},
    'plotcontour':{d:'',p:'Expr(Xpr),[LstVar],[LstVal]',a:['contourplot','DrwCtour']},
    'plotdensity':{d:'',p:'Expr,[x=xrange,y=yrange],[z],[xstep],[ystep]',a:['densityplot']},
    'plotfield':{d:'',p:'Expr,VectVar,[Opt]',a:['fieldplot']},
    'plotfunc':{d:'',p:'Expr,[Var(x) or VectVar] ,[Intg(color)]',a:['funcplot','DrawFunc','Graph']},
    'plotimplicit':{d:'',p:'Expr,Var1,Var2',a:['implicitplot']},
    'plotinequation':{d:'',p:'Expr,[x=xrange,y=yrange],[xstep],[ystep]',a:['inequationplot']},
    'plotode':{d:'',p:'Expr,VectVar,VectInitCond',a:['odeplot']},
    'plotparam':{d:'',p:'Cplx||Lst,Var||Lst(Var)',a:['paramplot','DrawParm','courbe_parametrique']},
    'plotpolar':{d:'',p:'Expr,Var,VarMin,VarMax',a:['polarplot','DrawPol','courbe_polaire']},
    'plotproba':{d:'',p:'Matrix,[Vector]'},
    'plotseq':{d:'',p:'Expr(f(Var)),Var=[a,xm,xM],Intg(p)',a:['seqplot','graphe_suite']},
    'plotspectrum':{d:'',p:'Audio(clip),[range=a..b]'},
    'plotwav':{d:'',p:'Audio(clip),[range=a..b]'},
    'pmin':{d:'',p:'Mtrx(A)||Real(a),[Var]'},
    'point':{d:'',p:'Cplx(za)||Vect'},
    'point2d':{d:'',p:'SeqVar(A,B,C...)'},
    'point3d':{d:'',p:'SeqVar(A,B,C...)'},
    'point_width_1':{d:'',p:'Opt',a:['point_width_2','point_width_3','point_width_4','point_width_5','point_width_6','point_width_7','epaisseur_point_1','epaisseur_point_2','epaisseur_point_3','epaisseur_point_4','epaisseur_point_5','epaisseur_point_6','epaisseur_point_7']},
    'poisson':{d:'',p:'Real(mu),Intg(k)'},
    'poisson_cdf':{d:'',p:'Real(mu),Real(x)'},
    'poisson_icdf':{d:'',p:'Real(mu),Real(p)'},
    'poisson_window':{d:'',p:'Lst,[Real(a)],[Interval(n1..n2)]'},
    'polar':{d:'',p:'Crcle,Pnt or Cplxe(A)'},
    'polar_coordinates':{d:'',p:'Pnt or Cplx or LstRectCoord'},
    'polar_point':{d:'',p:'Real(r),Real(t)'},
    'pole':{d:'',p:'Crcle,Line'},
    'poly2symb':{d:'',p:'Lst,Var',a:['r2e']},
    'polygon':{d:'',p:'LstPnt||LstCplx'},
    'polygone_rempli':{d:'',p:'Intg(n)'},
    'polygonplot':{d:'',p:'Mtrx',a:['ligne_polygonale']},
    'polygonscatterplot':{d:'',p:'Mtrx',a:['ligne_polygonale_pointee']},
    'polyhedron':{d:'',p:'SeqPnt(A,B,C...)'},
    'polynom':{d:'',p:'Opt'},
    'polynomial_regression':{d:'',p:'Lst||Mtrx(A),[Lst],Intg(n)'},
    'polynomial_regression_plot':{d:'',p:'Lst||Mtrx(A),[Lst],Intg(n)'},
    'position':{d:'',p:'NULL or LstCoord'},
    'poslbdLMQ':{d:'',p:'Poly(P)'},
    'posubLMQ':{d:'',p:'Poly(P)'},
    'potential':{d:'',p:'Vect(V),VectVar'},
    'pour':{d:''},
    'pow':{d:'',p:'Intg(a),Intg(n)'},
    'pow2exp':{d:'',p:'Expr'},
    'power_regression':{d:'',p:'Lst|Mtrx(A),[Lst]'},
    'power_regression_plot':{d:'',p:'Lst||Mtrx(A),[Lst]'},
    'powerpc':{d:'',p:'Cercle,Pnt or Cplx'},
    'powexpand':{d:'',p:'Expr'},
    'powmod':{d:'',p:'Intg(a),Intg(n),Intg(p),[Expr(P(x))],[Var]',a:['powermod']},
    'prepend':{d:'',p:'Lst||Set||Str(L),Elem(n)'},
    'preval':{d:'',p:'Expr(F(Var)),Real(a),Real(b),[Var]'},
    'prevperm':{d:'',p:'Intg(n)'},
    'prevprime':{d:'',p:'Intg(a)'},
    'primpart':{d:'',p:'Poly(P),[Var]'},
    'print':{d:'',p:'Expr|| Str',a:['Disp']},
    'printf':{d:'',p:'Expr'},
    'prism':{d:'',p:'LstPnt([A,B,C,D]),Pnt(A1)'},
    'prism_graph':{d:'',p:'Intg(n)'},
    'proc':{d:''},
    'product':{d:'',p:'Expr||Lst,[Var||Lst],[Intg(a)],[Intg(b)],[Intg(p)]',a:['mul']},
    'program':{d:''},
    'projection':{d:'',p:'Curve,Pnt'},
    'proot':{d:'',p:'Vect||Poly,[Intg(n)]'},
    'propfrac':{d:'',p:'Frac or RatFrac',a:['propFrac']},
    'pruefer_code':{d:'',p:'Vect(S)|Graph(T)'},
    'psrgcd':{d:'',p:'Poly,Poly'},
    'ptayl':{d:'',p:'Expr||Poly(P(Var)),Var=Real || Real(a),[Order || Var]'},
    'purge':{d:'',p:'Var',a:['DelVar','del']},
    'pwd':{d:'',p:'NULL'},
    'pyramid':{d:'',p:'Pnt(A),Pnt(B),Pnt(C),[Pnt(D)]',a:['tetrahedron']},
    'python_compat':{d:'',p:'Intg(0) or 1'},
    'q2a':{d:'',p:'QuadraForm, VectVar'},
    'qr':{d:'',p:'Mtrx'},
    'quadrant1':{d:'',p:'Opt',a:['quadrant2','quadrant3','quadrant4']},
    'quadric':{d:'',p:'Expr,[Lst(Var)]'},
    'quadrilateral':{d:'',p:'Pnt(A)||Cplx,Pnt(B)||Cplx,Pnt(C)||Cplx,Pnt(D)||Cplx'},
    'quantile':{d:'',p:'Lst(l),Real(p)'},
    'quartile1':{d:'',p:'Lst||Mtrx,[Lst]'},
    'quartile3':{d:'',p:'Lst||Mtrx,[Lst]'},
    'quartiles':{d:'',p:'Lst||Mtrx,[Lst]'},
    'quest':{d:'',p:'Intg(n)',a:['entry']},
    'quo':{d:'',p:'(Vect or Poly),(Vect or Poly),[Var]'},
    'quorem':{d:'',p:'(Vect or Poly),(Vect or Poly),[Var]',a:['divide']},
    'quote':{d:'',p:'Expr',a:['hold']},
    'radians':{d:'',p:'Real(deg)'},
    'radical_axis':{d:'',p:'Crcle,Crcle'},
    'radius':{d:'',p:'Crcle'},
    'radius2':{d:'',p:'Crcle'},
    'rand':{d:'',p:'Intg(n) or Interval(p..n) or NULL,[Intg(b1) or Lst(L)],[Intg(b2)]',a:['random']},
    'randbetad':{d:'',p:'Real(a),Real(b)',a:['betavariate']},
    'randbinomial':{d:'',p:'Intg(n),Real(p)'},
    'randchisquare':{d:'',p:'Intg(n)'},
    'randexp':{d:'',p:'Real(a)',a:['expovariate']},
    'randfisher':{d:'',p:'Intg(n),Intg(m)'},
    'randgammad':{d:'',p:'Real(a),Real(b)',a:['gammavariate']},
    'randgeometric':{d:'',p:'Real(p)'},
    'randmarkov':{d:'',p:'Mtrx(M) || Vctr(v),Intg(i0),[Intg(n)]'},
    'randmultinomial':{d:'',p:'List(P),[List(K)]'},
    'randnorm':{d:'',p:'Real(mu),Real(sigma)',a:['randNorm','normalvariate']},
    'random_bipartite_graph':{d:'',p:'Intg(n)||Lst(a,b),Real(p)||Intg(m)'},
    'random_digraph':{d:'',p:'Intg(n)||Lst(V),Real(p)||Intg(m)'},
    'random_graph':{d:'',p:'Intg(n)||Lst(V),Real(p)||Intg(m)'},
    'random_network':{d:'',p:'Intg(a),Intg(b),[Real(p)],[opts]'},
    'random_planar_graph':{d:'',p:'Intg(n)||Lst(V),Real(p),[Intg(c)]'},
    'random_regular_graph':{d:'',p:'Intg(n)||Lst(V),Intg(d),[connected]'},
    'random_sequence_graph':{d:'',p:'Lst(L)'},
    'random_tournament':{d:'',p:'Intg(n)||Lst(V)'},
    'random_tree':{d:'',p:'Intg(n)||Lst(V),[Intg(d)||root[=Vrtx(v)]]'},
    'random_variable':{d:'',p:'Lst(W)||Mtrx(M)||Fnc(f),[params]',a:['randvar']},
    'randperm':{d:'',p:'Intg(n)||Lst(L)',a:['shuffle']},
    'randpoisson':{d:'',p:'Real(λ)'},
    'randpoly':{d:'',p:'[Var(Var)],Intg(n),[law]',a:['randPoly']},
    'randstudent':{d:'',p:'Intg(n)'},
    'randvector':{d:'',p:'Intg(n), [Intg(m)],[Interval or quote(DistribLaw)]',a:['ranv']},
    'randweibulld':{d:'',p:'Real(a),Real(b)',a:['weibullvariate']},
    'range':{d:'',p:'Intg(n)||Intg(a),Intg(b),[Intg(p)]'},
    'rank':{d:'',p:'Mtrx'},
    'ranm':{d:'',p:'Intg(n), [Intg(m)],[Interval or quote(DistribLaw)]',a:['randMat','randmatrix']},
    'rat_jordan':{d:'',p:'Mtrx'},
    'ratinterp':{d:'',p:'[Mtrx(P) || List(X)],[List(Y)],[Var(x)],[Intg(d)])'},
    'rationalroot':{d:'',p:'Poly(P)'},
    'ratnormal':{d:'',p:'Expr'},
    'rdiv':{d:'',p:'Expr(a),Expr(b)'},
    're':{d:'',p:'Cplx or LstCplx',a:['real']},
    'reachable':{d:'',p:'Graph(G),Vrtx(u)'},
    'read':{d:'',p:'Str(fich_name)',a:['ramene']},
    'readrgb':{d:'',p:'Str(s),[Intg(w)],[Intg(h)]'},
    'readwav':{d:'',p:'Str(s)'},
    'realroot':{d:'',p:'[sturm],Poly(P),[Real(l)],[Cplx(a)],[Cplx(b)]'},
    'reciprocation':{d:'',p:'Crcle,Lst(Pnt,Line)'},
    'rect':{d:'',p:'Expr(x)'},
    'rectangle':{d:'',p:'Pnt(A)||Cplx,Pnt(B)||Cplx,Real(k)||Pnt(P)||Lst(P,k),[Var(D)],[Var(C)]'},
    'rectangle_plein':{d:'',p:'Real(a),[Real(b)]'},
    'rectangular_coordinates':{d:'',p:'LstPolCoord'},
    'recule':{d:'',p:'NULL or Real(n)',a:['backward']},
    'reduced_conic':{d:'',p:'Expr,[LstVar]'},
    'reduced_quadric':{d:'',p:'Expr, [LstVar]'},
    'ref':{d:'',p:'Mtrx(M)'},
    'reflection':{d:'',p:'(Pnt(A) or Line(D)),(Pnt(C) or Curve(C))'},
    'regroup':{d:'',p:'Expr'},
    'relabel_vertices':{d:'',p:'Graph(G),Lst(L)'},
    'reliability_polynomial':{d:'',p:'Graph(G),[Var(p)]'},
    'rem':{d:'',p:'(Vect or Poly),(Vect or Poly),[Var]'},
    'remove':{d:'',p:'FncBool(f)||a,Lst(l)'},
    'reorder':{d:'',p:'Expr, LstVar'},
    'repeat':{d:'',a:['until','repeter','jusqua','jusqu_a']},
    'repete':{d:'',p:'Intg,SeqCmds'},
    'resample':{d:'',p:'Audio(clip),[Intg(s),[Intg(q)]]'},
    'residue':{d:'',p:'Expr,Var(v),Cplx(a)'},
    'restart':{d:'',p:'NULL'},
    'resultant':{d:'',p:'Poly,Poly,Var'},
    'return':{d:'',p:'Expr'},
    'reverse_graph':{d:'',p:'Graph(G)'},
    'reverse_rsolve':{d:'',p:'Vect(v)',a:['berlekamp_massey']},
    'revert':{d:'',p:'Expr'},
    'revlex':{d:'',p:'Opt'},
    'revlist':{d:'',p:'Lst(L)||Audio',a:['reverse']},
    'rgb':{d:'',p:'Lst(r,g,b)||Intg(rrggbb)||Str(rrggbb)||Color(c)'},
    'rgb2hsv':{d:'',p:'Lst(r,g,b)'},
    'rgb2xyz':{d:'',p:'Lst(r,g,b)||Color(c)'},
    'rhombus':{d:'',p:'Pnt(A)||Cplx,Pnt(B)||Cplx,Angle(a)||Pnt(P)||Lst(P,a)),[Var(C)],[Var(D)]'},
    'rhombus_point':{d:'',p:'Opt',a:['point_losange','plus_point','point_plus','square_point','point_carre','cross_point','point_croix','triangle_point','point_triangle','star_point','point_etoile','point_point','invisible_point','point_invisible']},
    'riemann_window':{d:'',p:'Lst,[Interval(n1..n2)]'},
    'right':{d:'',p:'Equal(a=b) or Interval(a..b) or Str,Intg',a:['rhs','droit']},
    'right_triangle':{d:'',p:'(Pnt(A) or Cplx),(Pnt(B) or Cplx),(Real(k) or Pnt(P) or Lst(P,k)),[Var(C)]'},
    'risch':{d:'',p:'Expr,[Var]'},
    'rm_a_z':{d:'',p:'NULL'},
    'rm_all_vars':{d:'',p:'NULL'},
    'rmbreakpoint':{d:'',p:'Intg'},
    'rmmod':{d:'',p:'Str(pwd)'},
    'rms':{d:'',p:'Lst(X)'},
    'rmwatch':{d:'',p:'Var'},
    'romberg':{d:'',p:'Expr(f(x)),Var(x),Real(a),Real(b)',a:['nInt']},
    'rond':{d:'',p:'Real(r),[Real(a)],[Real(b)]'},
    'root':{d:'',p:'Expr(a),Expr(b)'},
    'rootof':{d:'',p:'LstPoly(P),LstPoly(Q)'},
    'roots':{d:'',p:'Poly,[Var]'},
    'rotate':{d:'',p:'Lst||Str(L),[Intg(n)]'},
    'rotation':{d:'',p:'(Pnt(B) or Cplx or Dr3),Angle(a1),(Pnt(A) or Curve)'},
    'round':{d:'',p:'Real or Cplx,[Intg(n)]'},
    'row':{d:'',p:'Mtrx(A),Intg(n)||Interval(n1..n2)'},
    'rowAdd':{d:'',p:'Mtrx(A),Intg(n1),Intg(n2)'},
    'rowNorm':{d:'',p:'Vect or Mtrx',a:['rownorm']},
    'rowSwap':{d:'',p:'Mtrx(A),Intg(n1),Intg(n2)',a:['swaprow','rowswap','SWAPROW']},
    'rowdim':{d:'',p:'Mtrx',a:['nrows','rowDim']},
    'rowspace':{d:'',p:'Mtrx(A), [Var(d)]'},
    'rref':{d:'',p:'Mtrx(M),[Intg(k)]||Opt',a:['gaussjord']},
    'rsolve':{d:'',p:'(Expr or LstExpr),(Var or LstVar),(InitVal or LstInitVal)'},
    'rur':{d:'',p:'Intg(n)'},
    'rur_certify':{d:'',p:'Intg(n)'},
    'same':{d:'',p:'Expr,Expr'},
    'sample':{d:'',p:'Intg(n1),Intg(n2)'},
    'samplerate':{d:'',p:'Audio(clip)'},
    'saute':{d:'',p:'NULL or Real(n)'},
    'save_history':{d:'',p:'Str(str)'},
    'scale':{d:'',p:'Mtrx(A),Expr(Xpr),Intg(n1)',a:['SCALE']},
    'scaleadd':{d:'',p:'Mtrx(A),Expr(Xpr),Intg(n1),Intg(n2)',a:['SCALEADD']},
    'scatterplot':{d:'',p:'Mtrx',a:['nuage_points']},
    'sec':{d:'',p:'Expr'},
    'segment':{d:'',p:'(Pnt or Cplx or Lst([xM,yM])),(Pnt or Cplx or Lst([xN,yN]),[Var],[Var] or Opt'},
    'seidel_spectrum':{d:'',p:'Graph(G)'},
    'seidel_switch':{d:'',p:'Graph(G),Lst(V)'},
    'select':{d:'',p:'FncBool(f),Lst(l)'},
    'semi_augment':{d:'',p:'Mtrx(A),Mtrx(B)'},
    'seq':{d:'',p:'Expr(Xpr),Var(Var)=Int(a..b),[Real(p)]||Expr(Xpr),Var(Var),Real(a),Real(b),[Real(p)]'},
    'seqsolve':{d:'',p:'(Expr or LstExpr),(Var or LstVar),(InitVal or LstInitVal)'},
    'sequence_graph':{d:'',p:'Lst(L)'},
    'series':{d:'',p:'Expr,Equal(var=limit_point),[Order],[Dir(1,0,-1)]'},
    'set[]':{d:'',p:'Seq',a:['%{%}']},
    'set_channel_data':{d:'',p:'Audio(clip),Lst||Mtrx(data),[Intg(offset),Intg(chn)]||Image(img),Intg(chn),Intg(x),Intg(y),Mtrx(data)'},
    'set_edge_attribute':{d:'',p:'Graph(G),Edge(e),Seq(tag1=value1,tag2=value2,..)'},
    'set_edge_weight':{d:'',p:'Graph(G),Edge(e),Real(w)'},
    'set_graph_attribute':{d:'',p:'Graph(G),Seq(tag1=value1,tag2=value2,..)'},
    'set_pixel':{d:'',p:'Intg(x),Intg(y),Intg(col)',a:['draw_pixel']},
    'set_screen':{d:'',p:'Intg(x),Intg(y)'},
    'set_vertex_attribute':{d:'',p:'Graph(G),Vrtx(v),Seq(tag1=value1,tag2=value2,..)'},
    'set_vertex_positions':{d:'',p:'Graph(G),Lst(vp)'},
    'shift':{d:'',p:'Lst,[Intg(n)]'},
    'shift_phase':{d:'',p:'Expr'},
    'shortest_path':{d:'',p:'Graph(G),Vrtx(s),Vrtx(t)||Lst(T)'},
    'show_pixels':{d:'',p:'NULL'},
    'si':{d:'',a:['alors','sinon','fsi']},
    'sierpinski_graph':{d:'',p:'Intg(n),Intg(k),[triangle]'},
    'sign':{d:'',p:'Expr'},
    'sign2Heaviside':{d:'',p:'Expr'},
    'signature':{d:'',p:'Permut'},
    'signe':{d:'',p:'Str(s)'},
    'similarity':{d:'',p:'Pnt or Dr3,Real,Angle,Pnt'},
    'simp2':{d:'',p:'Intg(A) or Poly(A),Intg(B) or Poly(B)'},
    'simplex_reduce':{d:'',p:'Mtrx(A), Vect(b), Vect(c)'},
    'simplicial_vertices':{d:'',p:'Graph(G)'},
    'simplify':{d:'',p:'Expr',a:['simplifier']},
    'simplifyDirac':{d:'',p:'Expr,[Seq(vars)]'},
    'simpson':{d:'',p:'Opt',a:['rombergt','rombergm','gauss15']},
    'simulated_annealing':{d:'',p:'x0,Func(cost),Func(dist),Func(step),Lst(csparam),[Lst(iterparam),[Real(maxstep)]]'},
    'simult':{d:'',p:'Mtrx(A),Mtrx(B)'},
    'sin':{d:'',p:'Expr or Opt',a:['SIN']},
    'sin2costan':{d:'',p:'Expr'},
    'sinc':{d:'',p:'Expr(x)'},
    'sincos':{d:'',p:'Expr or Opt'},
    'single_inter':{d:'',p:'Curve,Curve,[Pnt(A)||LstPnt(L)]',a:['line_inter']},
    'sinh':{d:'',p:'Expr'},
    'size':{d:'',p:'Lst||Str||Seq||Image||Audio',a:['nops','length','len']},
    'sizes':{d:'',p:'Lst or Str or Seq'},
    'slope':{d:'',p:'Line||Pnt||Cplx,[Pnt||Cplx]'},
    'slopeat':{d:'',p:'Line, Pnt||Cplx(z0)'},
    'slopeatraw':{d:'',p:'Line, Pnt||Cplx(z0)'},
    'smith':{d:'',p:'Matr(A)'},
    'smod':{d:'',p:'Intg,Intg',a:['mods']},
    'solve':{d:'',p:'Expr,[Var]',a:['resoudre']},
    'sommet':{d:'',p:'Op or Fnct'},
    'sort':{d:'',p:'LstReal or Seq [Fnc]',a:['sorted']},
    'sorta':{d:'',p:'LstReal||Seq×||Mtrx'},
    'sortd':{d:'',p:'LstReal||Seq||Mtrx'},
    'sortperm':{d:'',p:'Lst(V),[Permu(P)]'},
    'soundsec':{d:'',p:'Intg(n),[Intg(N)]'},
    'spanning_tree':{d:'',p:'Graph(G),[Vrtx(r)]'},
    'sphere':{d:'',p:'(Pnt or Vect),(Pnt or Real)'},
    'splice':{d:'',p:'Audio(clip1),Audio(clip2),[Intg(len),Real(p)]'},
    'spline':{d:'',p:'Lst(lx),Lst(ly),Var(x),Intg(d)'},
    'split':{d:'',p:'(Expr(Xpr),Lst(var1,var2))||(Str(s),Str(sep))'},
    'spring':{d:'',p:'Opt'},
    'sq':{d:'',p:'Seq'},
    'sqrfree':{d:'',p:'Expr'},
    'sqrt':{d:'',p:'Expr'},
    'square':{d:'',p:'(Pnt(A) or Cplx),(Pnt(B) or Cplx),[Pnt(P),Var(C),Var(D)]'},
    'srand':{d:'',a:['randseed']},
    'sst':{d:'',p:'NULL'},
    'sst_in':{d:'',p:'NULL'},
    'st_ordering':{d:'',p:'Graph(G),Vrtx(s),Vrtx(t)'},
    'stack':{d:''},
    'star_graph':{d:'',p:'Intg(n)'},
    'stddev':{d:'',p:'Lst||Mtrx,[Lst]',a:['ecart_type']},
    'stddevp':{d:'',p:'Lst||Mtrx,[Lst]',a:['stdDev','ecart_type_population']},
    'step':{d:'',a:['by','pas']},
    'stereo2mono':{d:'',p:'Audio(clip)'},
    'stft':{d:'',p:'Lst(data)'},
    'sto':{d:'',p:'(Real or Str),Var',a:['Store']},
    'str':{d:'',p:'Expr or Opt',a:['string']},
    'strip':{d:'',p:'Str(s)'},
    'strongly_connected_components':{d:'',p:'Graph(G)'},
    'student':{d:'',p:'Intg(n),Real(x0)',a:['studentd']},
    'student_cdf':{d:'',p:'Intg(n),Real(x0)'},
    'student_icdf':{d:'',p:'Intg(n),Real(p)'},
    'studentt':{d:'',p:'Lst,Real,[Real],Fnc,[Real]'},
    'sturm':{d:'',p:'Poly,[Var],[Cplx(a)],[Cplx(b)]'},
    'sturmab':{d:'',p:'Poly,Var,Cplx(a),Cplx(b)'},
    'sturmseq':{d:'',p:'Poly,[Var]'},
    'style':{d:'',p:'Opt'},
    'subMat':{d:'',p:'Mtrx(A),Intg(n1),Intg(n2),Intg(n3),Intg(n4).'},
    'subdivide_edges':{d:'',p:'Graph(G),Lst(E),[Intg(r)]'},
    'subgraph':{d:'',p:'Graph(G),Lst(E)'},
    'subs':{d:'',p:'Expr or Var=value,Var=value or Expr'},
    'subsop':{d:'',p:'Lst||Mtrx,Intg(n)=Expr'},
    'subst':{d:'',p:'Expr,Var(v)=value(a)',a:['substituer']},
    'subtype':{d:'',p:'Expr'},
    'sum':{d:'',p:'Expr,Var,VarMin(a),VarMax(b),[VarStep(p)]',a:['somme','add']},
    'sum_riemann':{d:'',p:'Expr(Xpr),Lst(var1,var2)'},
    'suppress':{d:'',p:'Vect(L)||Str(l),Intg(n)'},
    'surd':{d:'',p:'Expr,Intg(n)'},
    'svd':{d:'',p:'Mtrx(A)'},
    'switch':{d:''},
    'switch_axes':{d:'',p:'[Intg(0 or 1)]'},
    'sylvester':{d:'',p:'Poly,Poly,Var'},
    'symb2poly':{d:'',p:'Expr, LstVar or [Var]',a:['e2r']},
    'symbol_array':{d:'',p:'Strng(str),Seq(dim)'},
    'syst2mat':{d:'',p:'LstLinEq,LstVar'},
    'syzygy':{d:'',p:'List'},
    'table':{d:'',p:'SeqEqual(index=value)'},
    'tablefunc':{d:'',p:'Expr,Var'},
    'tableseq':{d:'',p:'Expr,(Var or LstVar),(InitVal or LstInitVal)'},
    'tabsign':{d:'',p:'Expr,Var'},
    'tabvar':{d:'',p:'Expr,Var'},
    'tail':{d:'',p:'Lst or Seq or Str'},
    'tan':{d:'',p:'Expr',a:['TAN']},
    'tan2cossin2':{d:'',p:'Expr'},
    'tan2sincos':{d:'',p:'Expr'},
    'tan2sincos2':{d:'',p:'Expr'},
    'tangent':{d:'',p:'Curve(C),Pnt(A)',a:['tangente']},
    'tanh':{d:'',p:'Expr'},
    'tantque':{d:''},
    'tar':{d:'',p:'String || Buffer || Buffer,String || Buffer,Int,String'},
    'taux_accroissement':{d:'',p:'Expr,Var,Val1,(Val1+Var or Val2)'},
    'taylor':{d:'',p:'Expr,[Var=limit_point],[Order]'},
    'tchebyshev1':{d:'',p:'Intg(n)'},
    'tchebyshev2':{d:'',p:'Intg(n)'},
    'tcoeff':{d:'',p:'Poly||Lst'},
    'tcollect':{d:'',p:'Expr',a:['tCollect','rassembler_trigo']},
    'tdeg':{d:'',p:'Opt'},
    'tensor_product':{d:'',p:'Seq(G1,G2,[G3])'},
    'test':{d:'',p:'Var'},
    'texpand':{d:'',p:'Expr',a:['tExpand','developper_transcendant']},
    'then':{d:''},
    'thickness':{d:'',p:'Opt',a:['epaisseur']},
    'thiele':{d:'',p:'[Mtrx(P) || List(X)],[List(Y)],[Var(x)]'},
    'threshold':{d:'',p:'Lst,Real(bound)[=Expr(repl)] or Lst[Real(lower)[=Expr(rl)],Real(upper)[=Expr(ru)]],[Fnc(compare)],[abs[=true or false]]'},
    'time':{d:'',p:'NULL'},
    'title':{d:'',p:'Opt',a:['titre']},
    'tlin':{d:'',p:'ExprTrig',a:['lineariser_trigo']},
    'tonnetz':{d:'',p:'Intg(a),Intg(b),Intg(c),[Intg(d)]'},
    'topologic_sort':{d:'',p:'Graph(G)',a:['topological_sort']},
    'torus_grid_graph':{d:'',p:'Intg(m),Intg(n)'},
    'total_degree':{d:'',p:'Poly(P),Lst(Vars)'},
    'tourne_droite':{d:'',p:'NULL or Real(n)'},
    'tourne_gauche':{d:'',p:'NULL or Real(n)'},
    'tpsolve':{d:'',p:'List(supply),List(demand),Mtrx(cost_matrix)'},
    'trace':{d:'',p:'Mtrx or GeoObj'},
    'trail':{d:'',p:'Seq(V)'},
    'trail2edges':{d:'',p:'Trail(T)'},
    'train':{d:'',p:'NeuralNet(net),Mtrx(input),Mtrx||Vect(expected_output),[Intg(batchsize)])'},
    'tran':{d:'',p:'Mtrx',a:['transpose']},
    'transitive_closure':{d:'',p:'Graph(G),[weighted[=true||false]]'},
    'translation':{d:'',p:'Vect, Pnt(C)'},
    'trapezoid':{d:'',p:'Opt',a:['middle_point','left_rectangle','right_rectangle','trapeze','point_milieu','rectangle_droit','rectangle_gauche']},
    'traveling_salesman':{d:'',p:'Graph(G),[Mtrx(M)],[opts]'},
    'tree':{d:'',p:'Opt'},
    'tree_height':{d:'',p:'Graph(T),[Vrtx(r)]'},
    'tri':{d:'',p:'Expr(x)'},
    'triangle':{d:'',p:'(Pnt or Cplx),(Pnt or Cplx),(Pnt or Cplx)'},
    'triangle_paper':{d:'',p:'Real(ux),Real(t),Real(uy),[x=xmin..xmax,y=ymin..ymax]'},
    'triangle_plein':{d:'',p:'Real(a),[Real(b)],[Real(t)]'},
    'triangle_window':{d:'',p:'Lst,[Intg(d)],[Interval(n1..n2)]'},
    'trig2exp':{d:'',p:'Expr'},
    'trigcos':{d:'',p:'Expr'},
    'trigexpand':{d:'',p:'Expr'},
    'triginterp':{d:'',p:'List,Var=xmin..xmax'},
    'trigsimplify':{d:'',p:'Expr'},
    'trigsin':{d:'',p:'Expr'},
    'trigtan':{d:'',p:'Expr'},
    'trim':{d:'',p:'(Str||Vect||Audio||Image)(s),[opts],[left|right],[index]'},
    'trn':{d:'',p:'Mtrx'},
    'true':{d:'',a:['TRUE','True']},
    'trunc':{d:'',p:'Real||LstReal,Int(n)'},
    'truncate':{d:'',p:'Poly(P),Intg(n)'},
    'truncate_graph':{d:'',p:'Graph(G)'},
    'try':{d:''},
    'tsimplify':{d:'',p:'Expr'},
    'tukey_window':{d:'',p:'Lst,[Real(a)],[Interval(n1..n2)]'},
    'tutte_polynomial':{d:'',p:'Graph(G),[Var(x),Var(y)]'},
    'two_edge_connected_components':{d:'',p:'Graph(G)'},
    'type':{d:'',p:'Expr'},
    'ufactor':{d:'',p:'Unit,Unit'},
    'ugamma':{d:'',p:'Real(a),Real(x),[1]'},
    'unapply':{d:'',p:'Expr,Var'},
    'unarchive':{d:'',p:'Str(namefich),Seq(Var)'},
    'undef':{d:''},
    'underlying_graph':{d:'',p:'Graph(G)'},
    'unfactored':{d:'',p:'Opt.',a:['sans_factoriser']},
    'uniform':{d:'',p:'Real(a),Real(b),Real(x)',a:['uniformd']},
    'uniform_cdf':{d:'',p:'Real(a),Real(b),Real(x0),[Real(y0)]',a:['uniformd_cdf']},
    'uniform_icdf':{d:'',p:'Real(a),Real(b),Real(p)',a:['uniformd_icdf']},
    'union':{d:'',p:'(Vect or Set),(Vect or Set)'},
    'unquote':{d:'',p:'Expr'},
    'upper':{d:'',p:'Mtrx||Strng'},
    'user_operator':{d:'',p:'Str(R),Fnc(f),Opt(Binary||Unary||Delete)'},
    'usimplify':{d:'',p:'Unit'},
    'valuation':{d:'',p:'Poly(P)',a:['ldegree']},
    'vandermonde':{d:'',p:'Vect(V)'},
    'variables_are_files':{d:'',p:':=Intg(0 or 1)'},
    'variance':{d:'',p:'Lst||Mtrx,[Lst]'},
    'vector':{d:'',p:'Pnt,Pnt || Pnt,Vect'},
    'vers':{d:'',p:'Real,Real'},
    'version':{d:'',p:'NULL'},
    'vertex_connectivity':{d:'',p:'Graph(G)'},
    'vertex_cover_number':{d:'',p:'Graph(G)'},
    'vertex_degree':{d:'',p:'Graph(G),Vrtx(v)'},
    'vertex_distance':{d:'',p:'Graph(G),Vrtx(s),Vrtx(t)||Lst(T)'},
    'vertex_in_degree':{d:'',p:'Graph(G),Vrtx(v)'},
    'vertex_out_degree':{d:'',p:'Graph(G),Vrtx(v)'},
    'vertices':{d:'',p:'Polygon or Polyedr(P)',a:['vertices_abc']},
    'vertices_abca':{d:'',p:'Polygon or Polyedr(P)'},
    'vpotential':{d:'',p:'Vect(V),LstVar'},
    'watch':{d:'',p:'Var'},
    'web_graph':{d:'',p:'Intg(a),Intg(b)'},
    'weibull':{d:'',p:'Real(k),Real(lambda),Real(theta),Real(x)',a:['weibulld']},
    'weibull_cdf':{d:'',p:'Real(k),Real(lambda),Real(theta),Real(x0)',a:['weibulld_cdf']},
    'weibull_icdf':{d:'',p:'Real(k),Real(lambda),Real(theta),Real(p)',a:['weibulld_icdf']},
    'weight_matrix':{d:'',p:'Graph(G)'},
    'weighted':{d:'',p:'Opt'},
    'weights':{d:'',p:'Opt'},
    'welch_window':{d:'',p:'Lst,[Interval(n1..n2)]'},
    'wheel_graph':{d:'',p:'Intg(n)'},
    'when':{d:'',p:'Cond,Expr1,Expr2'},
    'while':{d:''},
    'white':{d:'',p:'Opt',a:['black','red','green','blue','yellow','magenta','cyan','orange','purple','pink','grey','brown','olive','teal','navy','gold','violet']},
    'widget_size':{d:'',p:'Intg(n)'},
    'wilcoxonp':{d:'',p:'Intg,[Intg]'},
    'wilcoxons':{d:'',p:'List,List || Real'},
    'wilcoxont':{d:'',p:'List,List || Real,[Func],[Real]'},
    'with_sqrt':{d:'',p:':=Intg(0 or 1)'},
    'write':{d:'',p:'Str(fich_name),SeqVar',a:['sauve']},
    'writergb':{d:'',p:'Str(s),Lst'},
    'writewav':{d:'',p:'Str(s),Lst(l)'},
    'wz_certificate':{d:'',p:'Expr(U),[Expr(res)],[Var(n),Var(k)]'},
    'xcas_mode':{d:'',p:'Intg(0) or 1 or 2 or 3',a:['maple_mode']},
    'xml_print':{d:'',p:'Str'},
    'xor':{d:'',p:'Expr, Expr'},
    'xstep':{d:'',p:'Opt',a:['ystep','zstep','nstep','tstep','ustep','vstep']},
    'xyz2rgb':{d:'',p:'Lst(x,y,z)'},
    'xyztrange':{d:'',p:'SeqReal'},
    'zeros':{d:'',p:'Expr,[Var]'},
    'zip':{d:'',p:'Fnc2d(f),Lst(l1),Lst(l2),[Val(default)]'},
    'znorder':{d:'',p:'Intg'},
    'znprimroot':{d:'',p:'Intg'},
    'ztrans':{d:'',p:'Expr,[Var],[ZtransVar]'},
    '{}':{d:''},
    '|':{d:'',p:'Expr, Var(v1)=value(a1)[,v2=a2,...]'}
  },
  aliases: {
    '%':'mod',
    '%{%}':'set[]',
    '&&':'and',
    'ACOSH':'acosh',
    'ACOT':'acot',
    'ACSC':'acsc',
    'ASEC':'asec',
    'ASIN':'asin',
    'ASINH':'asinh',
    'ATAN':'atan',
    'ATANH':'atanh',
    'COS':'cos',
    'COSH':'cosh',
    'COT':'cot',
    'CSC':'csc',
    'ClrDraw':'ClrGraph',
    'DIGITS':'Digits',
    'DOM_int':'DOM_INT',
    'DelVar':'purge',
    'Disp':'print',
    'DrawFunc':'plotfunc',
    'DrawParm':'plotparam',
    'DrawPol':'plotpolar',
    'DrwCtour':'plotcontour',
    'ERROR':'error',
    'EXP':'exp',
    'EndDlog':'Dialog',
    'FALSE':'false',
    'False':'false',
    'Graph':'plotfunc',
    'IFTE':'ifte',
    'Input':'input',
    'LN':'ln',
    'NORMALD':'normald',
    'Output':'output',
    'Phi':'euler',
    'Pi':'pi',
    'PopUp':'choosebox',
    'ReLU':'MSE',
    'SCALE':'scale',
    'SCALEADD':'scaleadd',
    'SIN':'sin',
    'SWAPCOL':'colSwap',
    'SWAPROW':'rowSwap',
    'Store':'sto',
    'TAN':'tan',
    'TRUE':'true',
    'TeX':'latex',
    'True':'true',
    '[..]':'i[]',
    'adaptive':'MSE',
    'add':'sum',
    'alors':'si',
    'approx':'evalf',
    'arccos':'acos',
    'arccosh':'acosh',
    'arclen':'arcLen',
    'arcsin':'asin',
    'arcsinh':'asinh',
    'arctan':'atan',
    'arctanh':'atanh',
    'areaplot':'plotarea',
    'augment':'concat',
    'backward':'recule',
    'barplot':'bar_plot',
    'berlekamp_massey':'reverse_rsolve',
    'betavariate':'randbetad',
    'bezout_entiers':'iegcd',
    'black':'white',
    'block_size':'MSE',
    'blue':'white',
    'brent_solver':'bisection_solver',
    'brown':'white',
    'by':'step',
    'cSolve':'csolve',
    'cap_flat_line':'dash_line',
    'cap_round_line':'dash_line',
    'cap_square_line':'dash_line',
    'cauchyd':'cauchy',
    'cauchyd_cdf':'cauchy_cdf',
    'cauchyd_icdf':'cauchy_icdf',
    'ceiling':'ceil',
    'cfactor':'cFactor',
    'charpoly':'pcar',
    'chisquared':'chisquare',
    'chisquared_cdf':'chisquare_cdf',
    'chisquared_icdf':'chisquare_icdf',
    'chr':'char',
    'close':'fclose',
    'coeffs':'coeff',
    'colDim':'coldim',
    'colnorm':'colNorm',
    'color':'display',
    'colswap':'colSwap',
    'complex':'DOM_COMPLEX',
    'cond':'COND',
    'contourplot':'plotcontour',
    'convertir':'convert',
    'courbe_parametrique':'plotparam',
    'courbe_polaire':'plotpolar',
    'crossP':'cross',
    'cross_entropy':'MSE',
    'cross_point':'rhombus_point',
    'crossproduct':'cross',
    'cumsum':'cumSum',
    'cyan':'white',
    'dashdot_line':'dash_line',
    'dashdotdot_line':'dash_line',
    'deSolve':'desolve',
    'del':'purge',
    'densityplot':'plotdensity',
    'derive':'diff',
    'deriver':'diff',
    'developper':'expand',
    'developper_transcendant':'texpand',
    'divide':'quorem',
    'divisors':'idivis',
    'divmod':'iquorem',
    'dotP':'dot',
    'dotprod':'dot',
    'double':'DOM_FLOAT',
    'draw_pixel':'set_pixel',
    'droit':'right',
    'dsolve':'desolve',
    'e2r':'symb2poly',
    'ecart_type':'stddev',
    'ecart_type_population':'stddevp',
    'eigVc':'egv',
    'eigVl':'egvl',
    'eigenvalues':'eigenvals',
    'eigenvectors':'egv',
    'eigenvects':'egv',
    'end_for':'end',
    'end_if':'end',
    'end_while':'end',
    'entry':'quest',
    'epaisseur':'thickness',
    'epaisseur_ligne_1':'line_width_1',
    'epaisseur_ligne_2':'line_width_1',
    'epaisseur_ligne_3':'line_width_1',
    'epaisseur_ligne_4':'line_width_1',
    'epaisseur_ligne_5':'line_width_1',
    'epaisseur_ligne_6':'line_width_1',
    'epaisseur_ligne_7':'line_width_1',
    'epaisseur_point_1':'point_width_1',
    'epaisseur_point_2':'point_width_1',
    'epaisseur_point_3':'point_width_1',
    'epaisseur_point_4':'point_width_1',
    'epaisseur_point_5':'point_width_1',
    'epaisseur_point_6':'point_width_1',
    'epaisseur_point_7':'point_width_1',
    'est_permu':'is_permu',
    'et':'and',
    'evala':'normal',
    'evalm':'eval',
    'exact':'float2rational',
    'execute':'expr',
    'exponentiald':'exponential',
    'exponentiald_cdf':'exponential_cdf',
    'exponentiald_icdf':'exponential_icdf',
    'expovariate':'randexp',
    'expression':'DOM_SYMBOLIC',
    'extend':'concat',
    'facteurs_premiers':'ifactors',
    'factoriser':'factor',
    'factoriser_entier':'ifactor',
    'factoriser_sur_C':'cFactor',
    'faire':'do',
    'falsepos_solver':'bisection_solver',
    'fdistrib':'expand',
    'ffaire':'end',
    'ffonction':'end',
    'ffunction':'end',
    'fi':'end',
    'fieldplot':'plotfield',
    'fisherd':'fisher',
    'fisherd_cdf':'fisher_cdf',
    'fisherd_icdf':'fisher_icdf',
    'float':'DOM_FLOAT',
    'fonction':'function',
    'fonction_derivee':'function_diff',
    'forward':'avance',
    'fpour':'end',
    'frac':'fPart',
    'from':'de',
    'fsi':'end',
    'ftantque':'end',
    'fullparfrac':'parfrac',
    'func':'DOM_FUNC',
    'funcplot':'plotfunc',
    'fxnd':'f2nd',
    'gammavariate':'randgammad',
    'gauche':'left',
    'gauss15':'simpson',
    'gaussjord':'rref',
    'gcdex':'egcd',
    'gl_y':'gl_x',
    'gl_y_axis_color':'gl_x_axis_color',
    'gl_y_axis_name':'gl_x_axis_name',
    'gl_y_axis_unit':'gl_x_axis_unit',
    'gl_ytick':'gl_xtick',
    'gl_z':'gl_x',
    'gl_z_axis_color':'gl_x_axis_color',
    'gl_z_axis_name':'gl_x_axis_name',
    'gl_z_axis_unit':'gl_x_axis_unit',
    'gl_ztick':'gl_xtick',
    'gold':'white',
    'graphe':'plot',
    'graphe3d':'plot3d',
    'graphe_suite':'plotseq',
    'green':'white',
    'grey':'white',
    'heading':'cap',
    'hold':'quote',
    'hybrid_solver':'dnewton_solver',
    'hybridj_solver':'dnewton_solver',
    'hybrids_solver':'dnewton_solver',
    'hybridsj_solver':'dnewton_solver',
    'ichrem':'ichinrem',
    'identifier':'DOM_IDENT',
    'idn':'identity',
    'igcd':'gcd',
    'igcdex':'iegcd',
    'imag':'im',
    'implicitplot':'plotimplicit',
    'indets':'lname',
    'inequationplot':'plotinequation',
    'inf':'+infinity',
    'intDiv':'iquo',
    'integer':'DOM_INT',
    'integrate':'int',
    'integrer':'int',
    'interactive_odeplot':'interactive_plotode',
    'inverse':'inv',
    'invisible_point':'rhombus_point',
    'invlaplace':'ilaplace',
    'iratrecon':'fracmod',
    'isPrime':'isprime',
    'jusqu_a':'repeat',
    'jusqua':'repeat',
    'kde':'kernel_density',
    'kernel':'ker',
    'l2norm':'norm',
    'ldegree':'valuation',
    'learning_rate':'MSE',
    'left_rectangle':'trapezoid',
    'len':'size',
    'length':'size',
    'lhs':'left',
    'ligne_chapeau_carre':'dash_line',
    'ligne_chapeau_plat':'dash_line',
    'ligne_chapeau_rond':'dash_line',
    'ligne_polygonale':'polygonplot',
    'ligne_polygonale_pointee':'polygonscatterplot',
    'ligne_tiret':'dash_line',
    'ligne_tiret_point':'dash_line',
    'ligne_tiret_pointpoint':'dash_line',
    'ligne_trait_plein':'dash_line',
    'limite':'limit',
    'line_inter':'single_inter',
    'line_width_2':'line_width_1',
    'line_width_3':'line_width_1',
    'line_width_4':'line_width_1',
    'line_width_5':'line_width_1',
    'line_width_6':'line_width_1',
    'line_width_7':'line_width_1',
    'lineariser':'lin',
    'lineariser_trigo':'tlin',
    'lis':'input',
    'lis_phrase':'InputStr',
    'log':'ln',
    'log_loss':'MSE',
    'lp_bestlocalbound':'lp_assume',
    'lp_bestprojection':'lp_assume',
    'lp_binary':'lp_assume',
    'lp_binaryvariables':'lp_assume',
    'lp_breadthfirst':'lp_assume',
    'lp_depthfirst':'lp_assume',
    'lp_depthlimit':'lp_assume',
    'lp_firstfractional':'lp_assume',
    'lp_gaptolerance':'lp_assume',
    'lp_heuristic':'lp_assume',
    'lp_hybrid':'lp_assume',
    'lp_integer':'lp_assume',
    'lp_integervariables':'lp_assume',
    'lp_interiorpoint':'lp_assume',
    'lp_iterationlimit':'lp_assume',
    'lp_lastfractional':'lp_assume',
    'lp_maxcuts':'lp_assume',
    'lp_maximize':'lp_assume',
    'lp_method':'lp_assume',
    'lp_mostfractional':'lp_assume',
    'lp_nodelimit':'lp_assume',
    'lp_nodeselect':'lp_assume',
    'lp_nonnegative':'lp_assume',
    'lp_nonnegint':'lp_assume',
    'lp_presolve':'lp_assume',
    'lp_pseudocost':'lp_assume',
    'lp_simplex':'lp_assume',
    'lp_timelimit':'lp_assume',
    'lp_varselect':'lp_assume',
    'lp_verbose':'lp_assume',
    'lsq':'LSQ',
    'magenta':'white',
    'maple_mode':'xcas_mode',
    'middle_point':'trapezoid',
    'mods':'smod',
    'momentum':'MSE',
    'moustache':'boxwhisker',
    'moyenne':'mean',
    'mul':'product',
    'multiplier_conjugue':'mult_conjugate',
    'multiplier_conjugue_complexe':'mult_c_conjugate',
    'nCr':'comb',
    'nInt':'romberg',
    'nPr':'perm',
    'navy':'white',
    'ncols':'coldim',
    'newton_solver':'bisection_solver',
    'newtonj_solver':'dnewton_solver',
    'nlp_binary':'nlp_initialpoint',
    'nlp_binaryvariables':'nlp_initialpoint',
    'nlp_integer':'nlp_initialpoint',
    'nlp_integervariables':'nlp_initialpoint',
    'nlp_iterationlimit':'nlp_initialpoint',
    'nlp_maximize':'nlp_initialpoint',
    'nlp_method':'nlp_initialpoint',
    'nlp_nonnegative':'nlp_initialpoint',
    'nlp_nonnegint':'nlp_initialpoint',
    'nlp_precision':'nlp_initialpoint',
    'nlp_presolve':'nlp_initialpoint',
    'nlp_tolerance':'nlp_initialpoint',
    'nlp_verbose':'nlp_initialpoint',
    'non':'not',
    'nonnegint':'lp_assume',
    'nops':'size',
    'normald_cdf':'normal_cdf',
    'normald_icdf':'normal_icdf',
    'normalvariate':'randnorm',
    'nrows':'rowdim',
    'nstep':'xstep',
    'nuage_points':'scatterplot',
    'nullspace':'ker',
    'od':'end',
    'odeplot':'plotode',
    'olive':'white',
    'op':'feuille',
    'orange':'white',
    'otherwise':'default',
    'ou':'or',
    'paramplot':'plotparam',
    'pas':'step',
    'pcoef':'pcoeff',
    'pencolor':'crayon',
    'pendown':'baisse_crayon',
    'penup':'leve_crayon',
    'pie':'camembert',
    'pink':'white',
    'plotimf':'imfplot',
    'plotlist':'listplot',
    'plus_point':'rhombus_point',
    'point_carre':'rhombus_point',
    'point_croix':'rhombus_point',
    'point_etoile':'rhombus_point',
    'point_invisible':'rhombus_point',
    'point_losange':'rhombus_point',
    'point_milieu':'trapezoid',
    'point_plus':'rhombus_point',
    'point_point':'rhombus_point',
    'point_triangle':'rhombus_point',
    'point_width_2':'point_width_1',
    'point_width_3':'point_width_1',
    'point_width_4':'point_width_1',
    'point_width_5':'point_width_1',
    'point_width_6':'point_width_1',
    'point_width_7':'point_width_1',
    'polarplot':'plotpolar',
    'polyEval':'peval',
    'powermod':'powmod',
    'propFrac':'propfrac',
    'purple':'white',
    'quadrant2':'quadrant1',
    'quadrant3':'quadrant1',
    'quadrant4':'quadrant1',
    'r2e':'poly2symb',
    'ramene':'read',
    'randMat':'ranm',
    'randNorm':'randnorm',
    'randPoly':'randpoly',
    'randmatrix':'ranm',
    'random':'rand',
    'randseed':'srand',
    'randvar':'random_variable',
    'ranv':'randvector',
    'rassembler_trigo':'tcollect',
    'rational':'DOM_RAT',
    'real':'re',
    'rectangle_droit':'trapezoid',
    'rectangle_gauche':'trapezoid',
    'red':'white',
    'redim':'REDIM',
    'remain':'irem',
    'repeter':'repeat',
    'replace':'REPLACE',
    'resoudre':'solve',
    'resoudre_dans_C':'csolve',
    'resoudre_systeme_lineaire':'linsolve',
    'reverse':'revlist',
    'rhs':'right',
    'right_rectangle':'trapezoid',
    'rombergm':'simpson',
    'rombergt':'simpson',
    'rowDim':'rowdim',
    'rownorm':'rowNorm',
    'rowswap':'rowSwap',
    'sans_factoriser':'unfactored',
    'sauve':'write',
    'scalarProduct':'dot',
    'scalar_product':'dot',
    'schur':'SCHUR',
    'secant_solver':'bisection_solver',
    'seqplot':'plotseq',
    'shuffle':'randperm',
    'simplifier':'simplify',
    'sinon':'si',
    'sleep':'Pause',
    'snedecor':'fisher',
    'snedecor_cdf':'fisher_cdf',
    'snedecor_icdf':'fisher_icdf',
    'snedecord':'fisher',
    'snedecord_cdf':'fisher_cdf',
    'snedecord_icdf':'fisher_icdf',
    'solid_line':'dash_line',
    'somme':'sum',
    'sorted':'sort',
    'square_point':'rhombus_point',
    'star_point':'rhombus_point',
    'stdDev':'stddevp',
    'steffenson_solver':'bisection_solver',
    'string':'str',
    'studentd':'student',
    'substituer':'subst',
    'swapcol':'colSwap',
    'swaprow':'rowSwap',
    'symbol':'DOM_SYMBOLIC',
    'tCollect':'tcollect',
    'tExpand':'texpand',
    'tangente':'tangent',
    'teal':'white',
    'tetrahedron':'pyramid',
    'textinput':'InputStr',
    'throw':'error',
    'titre':'title',
    'to':'jusque',
    'topological_sort':'topologic_sort',
    'topology':'MSE',
    'trames':'frames',
    'transpose':'tran',
    'trapeze':'trapezoid',
    'triangle_point':'rhombus_point',
    'tstep':'xstep',
    'tuer':'kill',
    'uniformd':'uniform',
    'uniformd_cdf':'uniform_cdf',
    'uniformd_icdf':'uniform_icdf',
    'unitV':'normalize',
    'until':'repeat',
    'ustep':'xstep',
    'var':'local',
    'vertices_abc':'vertices',
    'violet':'white',
    'vstep':'xstep',
    'weibulld':'weibull',
    'weibulld_cdf':'weibull_cdf',
    'weibulld_icdf':'weibull_icdf',
    'weibullvariate':'randweibulld',
    'weight_decay':'MSE',
    'yellow':'white',
    'ystep':'xstep',
    'zstep':'xstep',
    '||':'or'
  }
};
